// Generated by CoffeeScript 2.7.0
(function() {
  var clean, safe;

  clean = function(txt) {
    var current, i, len, line, lines, outLines, ref, s;
    s = String(txt != null ? txt : '');
    s = s.replace(/{{{\s*First Name\s*}}}/gi, 'friend');
    s = s.replace(/{{{\s*first Name\s*}}}/g, 'friend');
    s = s.replace(/{{{\s*first name\s*}}}/gi, 'friend');
    s = s.replace(/{{{\s*comment:[^}]*}}}/gi, ' ');
    s = s.replace(/{{{\s*roar:[^}]*}}}/gi, ' ');
    s = s.replace(/{{{\s*death:[^}]*}}}/gi, ' ');
    s = s.replace(/{{{\s*RogerObt\s*}}}/g, ' ');
    s = s.replace(/{{{\s*Roger\s*}}}/g, 'Roger');
    s = s.replace(/{{{[^}]+}}}/g, ' ');
    s = s.replace(/{{[^}]+}}/g, ' ');
    s = s.replace(/https?:\/\/\S+/g, '');
    s = s.replace(/&(rsquo|lsquo|apos|#39);/gi, "'");
    s = s.replace(/&(rdquo|ldquo|quot);/gi, '"');
    s = s.replace(/&(mdash|ndash|hellip);/gi, ' ');
    s = s.replace(/&(nbsp|amp);/gi, ' ');
    s = s.replace(/&[a-zA-Z#0-9]+;/g, ' ');
    s = s.replace(/<\/?(html|body|p|br|sup|em|strong|div|span|blockquote|script|style|table|tr|td|ul|ol|li|a|img|h[1-6])\b[^>]*>/gi, ' ');
    s = s.replace(/<\/?[A-Za-z_][A-Za-z0-9:_-]*(\s+[^>]*)?>/g, ' ');
    s = s.replace(/\[([^\]]+)\]\[\d+\]/g, '$1');
    s = s.replace(/\[\d+\]/g, '');
    s = s.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');
    s = s.replace(/[_*]{1,3}([^*_]+)[_*]{1,3}/g, '$1');
    s = s.replace(/<<<|>>>/g, ' ');
    s = s.replace(/<stop>|<end>|<input>/gi, ' ');
    s = s.replace(/\bInput:|\bOutput:|\bPrompt:\s+\d+\s+tokens|\bGeneration:\s+\d+\s+tokens|\bPeak memory:/gi, ' ');
    s = s.replace(/[\u200B-\u200F\u2060\uFEFF\uFFFD]/g, '');
    s = s.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, ' ');
    s = s.replace(/[<>{}=+]{5,}/g, ' ');
    lines = s.split(/\r?\n/);
    outLines = [];
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      current = String(line != null ? line : '');
      current = current.replace(/^\s*>\s?/, '');
      current = current.replace(/^\s*#{1,6}\s+/, '');
      current = current.replace(/\s{2,}/g, ' ').trim();
      if (/^:\s*$/.test(current)) {
        continue;
      }
      if (/^please confirm\b/i.test(current)) {
        continue;
      }
      if (/^begin:\s*$/i.test(current)) {
        continue;
      }
      if (/^story fragment:\s*$/i.test(current)) {
        continue;
      }
      outLines.push(current);
    }
    lines = outLines;
    while (lines.length) {
      line = String((ref = lines[lines.length - 1]) != null ? ref : '').trim();
      if (!(/^:\s*https?:\/\/\S+\s*$/.test(line) || /^https?:\/\/\S+\s*$/.test(line))) {
        break;
      }
      lines.pop();
    }
    return lines.join("\n").replace(/\n{3,}/g, "\n\n").trim();
  };

  safe = function(title) {
    return String(title != null ? title : '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'untitled';
  };

  this.step = {
    desc: "Seed storyByID sqlite records from markdown stories",
    action: async function(S) {
      var buffer, currentTitle, existingStories, flushStory, i, j, k, len, len1, len2, line, lines, raw, ref, stories, story, storyID, storyIDs;
      existingStories = (ref = S.theLowdown('allStories.jsonl')) != null ? ref.value : void 0;
      if (!Array.isArray(existingStories)) {
        throw new Error(`[${S.stepName}] allStories.jsonl must be an array`);
      }
      if (existingStories.length > 0) {
        storyIDs = [];
        for (i = 0, len = existingStories.length; i < len; i++) {
          story = existingStories[i];
          storyID = story != null ? story.story_id : void 0;
          if (storyID == null) {
            continue;
          }
          storyIDs.push(storyID);
        }
        console.log("[seed_story_sqlite] sqlite already seeded, stories:", storyIDs.length);
        S.make('story_seed_ids', storyIDs);
        S.done();
        return;
      }
      raw = (await S.need('stories_md'));
      if (typeof raw !== 'string') {
        throw new Error(`[${S.stepName}] stories_md must be a string artifact`);
      }
      lines = raw.split(/\r?\n/);
      stories = [];
      currentTitle = null;
      buffer = [];
      flushStory = function() {
        var text;
        if (!((currentTitle != null) && buffer.length)) {
          return;
        }
        text = clean(buffer.join("\n"));
        if (text.length) {
          stories.push({
            story_id: safe(currentTitle),
            title: currentTitle,
            text: text
          });
        }
        return buffer = [];
      };
      for (j = 0, len1 = lines.length; j < len1; j++) {
        line = lines[j];
        if (line.startsWith('# ')) {
          flushStory();
          currentTitle = line.slice(2).trim();
        } else {
          buffer.push(line);
        }
      }
      flushStory();
      storyIDs = [];
      for (k = 0, len2 = stories.length; k < len2; k++) {
        story = stories[k];
        S.saveThis(`storyByID{${story.story_id}}.json`, story);
        storyIDs.push(story.story_id);
      }
      console.log("[seed_story_sqlite] stories seeded:", storyIDs.length);
      S.make('story_seed_ids', storyIDs);
      S.done();
    }
  };

}).call(this);
