// Generated by CoffeeScript 2.7.0
var coerceJSON, normalizeDiaryKag, readArtifactTarget, renderEvent, renderEventSupport, renderKagEntry;

renderEvent = function(event) {
  var headline, keyword, kind, lines, ref, ref1, ref2, ref3, text;
  kind = String((ref = event != null ? event.kind : void 0) != null ? ref : '').trim();
  text = String((ref1 = event != null ? event.text : void 0) != null ? ref1 : '').trim();
  keyword = String((ref2 = event != null ? event.keyword : void 0) != null ? ref2 : '').trim();
  headline = String((ref3 = event != null ? event.headline : void 0) != null ? ref3 : '').trim();
  lines = [];
  if (kind.length || text.length) {
    lines.push(`- ${kind}: ${text}`);
  }
  if (keyword.length) {
    lines.push(`  keyword: ${keyword}`);
  }
  if (headline.length) {
    lines.push(`  headline: ${headline}`);
  }
  return lines.join("\n");
};

renderKagEntry = function(entry) {
  var headline, keyword, ref, ref1;
  keyword = String((ref = entry != null ? entry.keyword : void 0) != null ? ref : '').trim();
  headline = String((ref1 = entry != null ? entry.headline : void 0) != null ? ref1 : '').trim();
  if (keyword.length && headline.length) {
    return `- ${keyword}: ${headline}`;
  }
  if (headline.length) {
    return `- ${headline}`;
  }
  if (keyword.length) {
    return `- ${keyword}`;
  }
  return "- unlabelled KAG cue";
};

renderEventSupport = function(kind, payload) {
  var chunkIndex, chunkText, emotion, headline, i, j, keyword, len, len1, line, lines, match, matches, metaBits, ref, ref1, ref2, ref3, ref4, ref5, ref6, storyID;
  if (!((payload != null) && typeof payload === 'object')) {
    return null;
  }
  emotion = String((ref = payload.selected_emotion) != null ? ref : '').trim();
  matches = (ref1 = payload.matches) != null ? ref1 : [];
  lines = [];
  lines.push(`${kind}:`);
  if (emotion.length) {
    lines.push(`  desired emotion: ${emotion}`);
  }
  if (matches.length === 0) {
    lines.push("  raw support: none");
    return lines.join("\n");
  }
  for (i = 0, len = matches.length; i < len; i++) {
    match = matches[i];
    storyID = String((ref2 = match != null ? match.story_id : void 0) != null ? ref2 : '').trim();
    chunkIndex = match != null ? match.chunk_index : void 0;
    keyword = String((ref3 = match != null ? match.keyword : void 0) != null ? ref3 : '').trim();
    headline = String((ref4 = match != null ? match.headline : void 0) != null ? ref4 : '').trim();
    chunkText = String((ref5 = match != null ? match.chunk_text : void 0) != null ? ref5 : '').trim();
    metaBits = [];
    if (storyID.length) {
      metaBits.push(storyID);
    }
    if (chunkIndex != null) {
      metaBits.push(`chunk ${chunkIndex}`);
    }
    if (keyword.length) {
      metaBits.push(keyword);
    }
    if (headline.length) {
      metaBits.push(headline);
    }
    lines.push(`  - ${metaBits.join(' / ')}`);
    if (chunkText.length) {
      ref6 = chunkText.split(/\r?\n/);
      for (j = 0, len1 = ref6.length; j < len1; j++) {
        line = ref6[j];
        lines.push(`    ${line}`);
      }
    }
  }
  return lines.join("\n");
};

coerceJSON = function(value) {
  if (typeof value !== 'string') {
    return value;
  }
  try {
    return JSON.parse(value);
  } catch (error) {
    return value;
  }
};

normalizeDiaryKag = function(value) {
  var out, parsedEntries, ref;
  value = coerceJSON(value);
  if (Array.isArray(value != null ? value.entries : void 0)) {
    return value;
  }
  if ((value != null) && typeof value === 'object' && !Array.isArray(value)) {
    if (Array.isArray((ref = value.value) != null ? ref.entries : void 0)) {
      return value.value;
    }
    if (typeof value.entries === 'string') {
      parsedEntries = coerceJSON(value.entries);
      if (Array.isArray(parsedEntries)) {
        out = Object.assign({}, value);
        out.entries = parsedEntries;
        return out;
      }
    }
  }
  return value;
};

readArtifactTarget = async function(L, artifactKey) {
  var experiment, ref, ref1, ref2, ref3, targetEntry, targetKey, targetValue;
  experiment = (ref = (ref1 = L.theLowdown('experiment.yaml')) != null ? ref1.value : void 0) != null ? ref : {};
  targetKey = experiment != null ? (ref2 = experiment.artifacts) != null ? (ref3 = ref2[artifactKey]) != null ? ref3.target : void 0 : void 0 : void 0;
  if (typeof targetKey !== 'string') {
    return void 0;
  }
  targetEntry = L.theLowdown(targetKey);
  targetValue = targetEntry != null ? targetEntry.value : void 0;
  if (targetValue === void 0) {
    if (typeof (targetEntry != null ? targetEntry.waitFor : void 0) === 'function') {
      targetValue = (await targetEntry.waitFor());
    } else if ((targetEntry != null ? targetEntry.notifier : void 0) != null) {
      targetValue = (await targetEntry.notifier);
    }
  }
  return targetValue;
};

this.step = {
  desc: "Build the final diary prompt from diary events and matched KAG",
  action: async function(L) {
    var diaryKag, entry, eventLines, i, kagLines, kind, len, prompt, ref, ref1, ref10, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, row, storyID, storyParts, supportLines;
    storyParts = (await L.need('story_parts'));
    diaryKag = (await L.need('diary_kag'));
    storyParts = coerceJSON(storyParts);
    diaryKag = normalizeDiaryKag(diaryKag);
    if (!((storyParts != null) && typeof storyParts === 'object' && !Array.isArray(storyParts))) {
      storyParts = (await readArtifactTarget(L, 'story_parts'));
      storyParts = coerceJSON(storyParts);
    }
    if (!Array.isArray(diaryKag != null ? diaryKag.entries : void 0)) {
      diaryKag = (await readArtifactTarget(L, 'diary_kag'));
      diaryKag = normalizeDiaryKag(diaryKag);
    }
    if (!((storyParts != null) && typeof storyParts === 'object' && !Array.isArray(storyParts))) {
      throw new Error(`[${L.stepName}] story_parts must be an object`);
    }
    if (!Array.isArray(diaryKag != null ? diaryKag.entries : void 0)) {
      throw new Error(`[${L.stepName}] diary_kag must be an object`);
    }
    eventLines = [];
    eventLines.push(renderEvent({
      kind: 'scene',
      text: (ref = storyParts.scene) != null ? ref.text : void 0,
      keyword: (ref1 = storyParts.scene) != null ? ref1.location : void 0,
      headline: ''
    }));
    eventLines.push(renderEvent({
      kind: 'arrival',
      text: (ref2 = storyParts.arrival) != null ? ref2.text : void 0,
      keyword: (ref3 = storyParts.arrival) != null ? ref3.character : void 0,
      headline: ''
    }));
    eventLines.push(renderEvent({
      kind: 'disturbance',
      text: (ref4 = storyParts.disturbance) != null ? ref4.text : void 0,
      keyword: (ref5 = storyParts.disturbance) != null ? ref5.theme : void 0,
      headline: ''
    }));
    eventLines.push(renderEvent({
      kind: 'reflection',
      text: (ref6 = storyParts.reflection) != null ? ref6.text : void 0,
      keyword: '',
      headline: ''
    }));
    eventLines.push(renderEvent({
      kind: 'realization',
      text: (ref7 = storyParts.realization) != null ? ref7.text : void 0,
      keyword: '',
      headline: ''
    }));
    eventLines = eventLines.filter(Boolean);
    kagLines = ((function() {
      var i, len, ref8, results;
      ref8 = diaryKag.entries;
      results = [];
      for (i = 0, len = ref8.length; i < len; i++) {
        entry = ref8[i];
        if (entry != null) {
          results.push(renderKagEntry(entry));
        }
      }
      return results;
    })()).filter(Boolean);
    supportLines = [];
    ref8 = ['scene', 'arrival', 'disturbance', 'reflection', 'realization'];
    for (i = 0, len = ref8.length; i < len; i++) {
      kind = ref8[i];
      row = renderEventSupport(kind, diaryKag != null ? (ref9 = diaryKag.events) != null ? ref9[kind] : void 0 : void 0);
      if (row != null) {
        supportLines.push(row);
      }
    }
    storyID = String((ref10 = storyParts.story_id) != null ? ref10 : '').trim();
    prompt = ["You are writing in the narrative voice of Jim from St. John's.", "", "Write a diary entry in first person.", "Use the diary events as the backbone of the entry.", "Use the KAG cues as emotional guidance, but keep the entry grounded and concrete.", "", "Rules:", "- Do not introduce plot contradictions", "- Add sensory detail and reflective narration", "- Keep the voice observational, slightly humorous, and reflective", "- Return only the finished diary entry", "", "Diary story id:", `${storyID}`, "", "Diary events:", eventLines.length ? eventLines.join("\n") : "- none", "", "Event raw support passages:", supportLines.length ? supportLines.join("\n\n") : "- none", "", "KAG cues:", kagLines.length ? kagLines.join("\n") : "- none", "Write the events in the following order: scene, arrival, disturbance, reflection, realization. make each one a separate paragraph in your writing."].join("\n");
    console.log("[build_diary_prompt_ite] story:", storyID);
    console.log("[build_diary_prompt_ite] prompt chars:", prompt.length);
    L.make('diary_prompt_text', prompt);
    L.done();
  }
};
