// Generated by CoffeeScript 2.7.0
(function() {
  var renderEvent, renderKagEntry;

  renderEvent = function(event) {
    var headline, keyword, kind, lines, ref, ref1, ref2, ref3, text;
    kind = String((ref = event != null ? event.kind : void 0) != null ? ref : '').trim();
    text = String((ref1 = event != null ? event.text : void 0) != null ? ref1 : '').trim();
    keyword = String((ref2 = event != null ? event.keyword : void 0) != null ? ref2 : '').trim();
    headline = String((ref3 = event != null ? event.headline : void 0) != null ? ref3 : '').trim();
    lines = [];
    if (kind.length || text.length) {
      lines.push(`- ${kind}: ${text}`);
    }
    if (keyword.length) {
      lines.push(`  keyword: ${keyword}`);
    }
    if (headline.length) {
      lines.push(`  headline: ${headline}`);
    }
    return lines.join("\n");
  };

  renderKagEntry = function(entry) {
    var headline, keyword, ref, ref1;
    keyword = String((ref = entry != null ? entry.keyword : void 0) != null ? ref : '').trim();
    headline = String((ref1 = entry != null ? entry.headline : void 0) != null ? ref1 : '').trim();
    if (keyword.length && headline.length) {
      return `- ${keyword}: ${headline}`;
    }
    if (headline.length) {
      return `- ${headline}`;
    }
    if (keyword.length) {
      return `- ${keyword}`;
    }
    return "- unlabelled KAG cue";
  };

  this.step = {
    desc: "Build the final diary prompt from diary events and matched KAG",
    action: async function(M, stepName) {
      var diaryEvents, diaryKag, entry, event, eventLines, eventsEntry, kagEntry, kagLines, prompt, ref, ref1, story, storyEntry, storyID, storyIDEntry;
      storyIDEntry = M.theLowdown('selected_story_id');
      storyID = storyIDEntry != null ? storyIDEntry.value : void 0;
      if (storyID === void 0) {
        if (typeof (storyIDEntry != null ? storyIDEntry.waitFor : void 0) === 'function') {
          storyID = (await storyIDEntry.waitFor());
        } else if ((storyIDEntry != null ? storyIDEntry.notifier : void 0) != null) {
          storyID = (await storyIDEntry.notifier);
        }
      }
      eventsEntry = M.theLowdown('diary_events');
      diaryEvents = eventsEntry != null ? eventsEntry.value : void 0;
      if (diaryEvents === void 0) {
        if (typeof (eventsEntry != null ? eventsEntry.waitFor : void 0) === 'function') {
          diaryEvents = (await eventsEntry.waitFor());
        } else if ((eventsEntry != null ? eventsEntry.notifier : void 0) != null) {
          diaryEvents = (await eventsEntry.notifier);
        }
      }
      kagEntry = M.theLowdown('diary_kag');
      diaryKag = kagEntry != null ? kagEntry.value : void 0;
      if (diaryKag === void 0) {
        if (typeof (kagEntry != null ? kagEntry.waitFor : void 0) === 'function') {
          diaryKag = (await kagEntry.waitFor());
        } else if ((kagEntry != null ? kagEntry.notifier : void 0) != null) {
          diaryKag = (await kagEntry.notifier);
        }
      }
      storyEntry = M.theLowdown(`storyByID{${storyID}}.json`);
      story = storyEntry != null ? storyEntry.value : void 0;
      if (story === void 0) {
        if (typeof (storyEntry != null ? storyEntry.waitFor : void 0) === 'function') {
          story = (await storyEntry.waitFor());
        } else if ((storyEntry != null ? storyEntry.notifier : void 0) != null) {
          story = (await storyEntry.notifier);
        }
      }
      if (typeof storyID !== 'string') {
        throw new Error(`[${stepName}] selected_story_id must be a string`);
      }
      if (!Array.isArray(diaryEvents != null ? diaryEvents.events : void 0)) {
        throw new Error(`[${stepName}] diary_events must be an object`);
      }
      if (!Array.isArray(diaryKag != null ? diaryKag.entries : void 0)) {
        throw new Error(`[${stepName}] diary_kag must be an object`);
      }
      if ((story != null ? story.text : void 0) == null) {
        throw new Error(`[${stepName}] Missing sqlite story ${storyID}`);
      }
      eventLines = ((function() {
        var i, len, ref, results;
        ref = diaryEvents.events;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          event = ref[i];
          if (event != null) {
            results.push(renderEvent(event));
          }
        }
        return results;
      })()).filter(Boolean);
      kagLines = ((function() {
        var i, len, ref, results;
        ref = diaryKag.entries;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          entry = ref[i];
          if (entry != null) {
            results.push(renderKagEntry(entry));
          }
        }
        return results;
      })()).filter(Boolean);
      prompt = ["You are writing in the narrative voice of Jim from St. John's.", "", "Write a diary entry in first person.", "Use the diary events as the backbone of the entry.", "Use the KAG cues as emotional guidance, but keep the entry grounded and concrete.", "", "Rules:", "- Keep the events in the listed order", "- Do not introduce plot contradictions", "- Add sensory detail and reflective narration", "- Keep the voice observational, slightly humorous, and reflective", "- Return only the finished diary entry", "", "Story source:", `${(ref = story.title) != null ? ref : storyID}`, "", "Diary events:", eventLines.length ? eventLines.join("\n") : "- none", "", "KAG cues:", kagLines.length ? kagLines.join("\n") : "- none", "", "Source text for grounding:", "", `${String((ref1 = story.text) != null ? ref1 : '').trim()}`].join("\n");
      console.log("[build_diary_prompt_ite] story:", storyID);
      console.log("[build_diary_prompt_ite] prompt chars:", prompt.length);
      M.saveThis('diary_prompt_text', prompt);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
