// Generated by CoffeeScript 2.7.0
var DatabaseSync, buildStoryGroups, coerceJSON, flattenEntries, path, queryEmotionMatches, splitParagraphs,
  hasProp = {}.hasOwnProperty;

path = require('path');

({DatabaseSync} = require('node:sqlite'));

coerceJSON = function(value) {
  if (typeof value !== 'string') {
    return value;
  }
  try {
    return JSON.parse(value);
  } catch (error) {
    return value;
  }
};

splitParagraphs = function(text) {
  var i, len, part, parts, rawPart, rawParts;
  rawParts = String(text != null ? text : '').split(/\n\s*\n/);
  parts = [];
  for (i = 0, len = rawParts.length; i < len; i++) {
    rawPart = rawParts[i];
    part = String(rawPart != null ? rawPart : '').replace(/\s+/g, ' ').trim();
    if (!part.length) {
      continue;
    }
    parts.push(part);
  }
  return parts;
};

buildStoryGroups = function(text) {
  var baseSize, groupIndex, groupSize, groups, i, paragraphs, remainder, selected, startIndex, total;
  paragraphs = splitParagraphs(text);
  if (!paragraphs.length) {
    return [];
  }
  if (paragraphs.length < 5) {
    return [
      {
        group_index: 1,
        text: paragraphs.join("\n\n")
      }
    ];
  }
  groups = [];
  total = paragraphs.length;
  baseSize = Math.floor(total / 5);
  remainder = total % 5;
  startIndex = 0;
  for (groupIndex = i = 0; i < 5; groupIndex = ++i) {
    groupSize = baseSize;
    if (groupIndex < remainder) {
      groupSize += 1;
    }
    selected = paragraphs.slice(startIndex, startIndex + groupSize);
    groups.push({
      group_index: groupIndex + 1,
      text: selected.join("\n\n")
    });
    startIndex += groupSize;
  }
  return groups;
};

queryEmotionMatches = function(db, emotionKeyword, limit) {
  var chunkIndex, dedupeKey, group, groups, i, len, matches, ref, ref1, ref2, ref3, ref4, row, rows, seen;
  if (!(typeof emotionKeyword === 'string' && emotionKeyword.trim().length)) {
    return [];
  }
  rows = db.prepare(`SELECT kag_entries.story_id, stories.title, stories.text, kag_entries.chunk_index, kag_entries.keyword, kag_entries.headline, kag_entries.entry_index
FROM kag_entries
INNER JOIN stories
  ON stories.story_id = kag_entries.story_id
WHERE kag_entries.keyword = ?
ORDER BY kag_entries.story_id ASC, kag_entries.chunk_index ASC, kag_entries.entry_index ASC`).all(emotionKeyword);
  matches = [];
  seen = new Set();
  for (i = 0, len = rows.length; i < len; i++) {
    row = rows[i];
    chunkIndex = Number(row != null ? row.chunk_index : void 0);
    if (!(Number.isFinite(chunkIndex) && chunkIndex > 0)) {
      continue;
    }
    groups = buildStoryGroups((ref = row != null ? row.text : void 0) != null ? ref : '');
    group = groups[chunkIndex - 1];
    if (group == null) {
      continue;
    }
    dedupeKey = `${row.story_id}|${chunkIndex}|${row.keyword}|${(ref1 = row.headline) != null ? ref1 : ''}`;
    if (seen.has(dedupeKey)) {
      continue;
    }
    seen.add(dedupeKey);
    matches.push({
      story_id: row.story_id,
      title: (ref2 = row.title) != null ? ref2 : null,
      chunk_index: chunkIndex,
      keyword: (ref3 = row.keyword) != null ? ref3 : null,
      headline: (ref4 = row.headline) != null ? ref4 : null,
      chunk_text: group.text
    });
    if (matches.length >= limit) {
      break;
    }
  }
  return matches;
};

flattenEntries = function(eventMap) {
  var entries, i, keyword, keywords, kind, len, match, payload, ref, ref1, ref2, ref3, seenKeywords;
  entries = [];
  keywords = [];
  seenKeywords = new Set();
  ref = eventMap != null ? eventMap : {};
  for (kind in ref) {
    if (!hasProp.call(ref, kind)) continue;
    payload = ref[kind];
    ref2 = (ref1 = payload != null ? payload.matches : void 0) != null ? ref1 : [];
    for (i = 0, len = ref2.length; i < len; i++) {
      match = ref2[i];
      entries.push({
        story_id: match.story_id,
        kind: kind,
        chunk_index: match.chunk_index,
        keyword: match.keyword,
        headline: match.headline,
        chunk_text: match.chunk_text
      });
      keyword = String((ref3 = match.keyword) != null ? ref3 : '').trim();
      if (!keyword.length) {
        continue;
      }
      if (seenKeywords.has(keyword)) {
        continue;
      }
      seenKeywords.add(keyword);
      keywords.push(keyword);
    }
  }
  return {entries, keywords};
};

this.step = {
  desc: "Collect exact KAG chunk matches for the selected diary event emotions",
  action: async function(L) {
    var db, dbPath, eventMap, flattened, i, kind, len, limit, limitRaw, matches, payload, ref, ref1, ref2, ref3, row, selectedEmotion, storyID, storyParts;
    storyParts = (await L.need('story_parts'));
    storyParts = coerceJSON(storyParts);
    if (!((storyParts != null) && typeof storyParts === 'object' && !Array.isArray(storyParts))) {
      throw new Error(`[${L.stepName}] story_parts must be an object`);
    }
    storyID = String((ref = storyParts.story_id) != null ? ref : '').trim();
    if (!storyID.length) {
      throw new Error(`[${L.stepName}] story_parts missing story_id`);
    }
    limitRaw = L.param('per_event_match_limit');
    limit = Number(limitRaw);
    if (!(Number.isFinite(limit) && limit > 0 && Math.floor(limit) === limit)) {
      throw new Error(`[${L.stepName}] per_event_match_limit must be a positive integer`);
    }
    dbPath = path.join(process.cwd(), 'runtime.sqlite');
    db = new DatabaseSync(dbPath);
    eventMap = {};
    try {
      ref1 = ['scene', 'arrival', 'disturbance', 'reflection', 'realization'];
      for (i = 0, len = ref1.length; i < len; i++) {
        kind = ref1[i];
        selectedEmotion = String((ref2 = L.param(`${kind}_emotion`, '')) != null ? ref2 : '').trim();
        matches = queryEmotionMatches(db, selectedEmotion, limit);
        eventMap[kind] = {
          kind: kind,
          selected_emotion: selectedEmotion,
          matches: matches
        };
      }
    } finally {
      try {
        db.close();
      } catch (error) {
        null;
      }
    }
    flattened = flattenEntries(eventMap);
    payload = {
      story_id: storyID,
      keywords: flattened.keywords,
      entries: flattened.entries,
      events: eventMap
    };
    console.log("[collect_diary_kag_ite] diary story:", storyID);
    for (kind in eventMap) {
      if (!hasProp.call(eventMap, kind)) continue;
      row = eventMap[kind];
      console.log(`[collect_diary_kag_ite] ${kind} emotion:`, (ref3 = row.selected_emotion) != null ? ref3 : '');
      console.log(`[collect_diary_kag_ite] ${kind} matches:`, row.matches.length);
    }
    L.make('diary_kag', payload);
    L.done();
  }
};
