// Generated by CoffeeScript 2.7.0
(function() {
  var scoreEntry, wordSet;

  wordSet = function(text) {
    var ref, words;
    words = (ref = String(text != null ? text : '').toLowerCase().match(/[a-z0-9]+/g)) != null ? ref : [];
    return new Set(words);
  };

  scoreEntry = function(entry, eventWords) {
    var i, len, ref, ref1, ref2, score, word, words;
    words = wordSet(`${(ref = entry != null ? entry.keyword : void 0) != null ? ref : ''} ${(ref1 = entry != null ? entry.headline : void 0) != null ? ref1 : ''}`);
    score = 0;
    if (String((ref2 = entry != null ? entry.keyword : void 0) != null ? ref2 : '').trim().length && eventWords.has(String(entry.keyword).toLowerCase())) {
      score += 3;
    }
    for (i = 0, len = words.length; i < len; i++) {
      word = words[i];
      if (eventWords.has(word)) {
        score += 1;
      }
    }
    return score;
  };

  this.step = {
    desc: "Collect the KAG entries that best fit the selected diary events",
    action: async function(M, stepName) {
      var chosen, diaryEvents, entry, event, eventWords, eventsEntry, i, idx, j, k, kag, kagEntry, keyword, keywordSet, keywords, l, len, len1, len2, len3, payload, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, row, scored, storyEntry, storyID, word;
      storyEntry = M.theLowdown('selected_story_id');
      storyID = storyEntry != null ? storyEntry.value : void 0;
      if (storyID === void 0) {
        if (typeof (storyEntry != null ? storyEntry.waitFor : void 0) === 'function') {
          storyID = (await storyEntry.waitFor());
        } else if ((storyEntry != null ? storyEntry.notifier : void 0) != null) {
          storyID = (await storyEntry.notifier);
        }
      }
      eventsEntry = M.theLowdown('diary_events');
      diaryEvents = eventsEntry != null ? eventsEntry.value : void 0;
      if (diaryEvents === void 0) {
        if (typeof (eventsEntry != null ? eventsEntry.waitFor : void 0) === 'function') {
          diaryEvents = (await eventsEntry.waitFor());
        } else if ((eventsEntry != null ? eventsEntry.notifier : void 0) != null) {
          diaryEvents = (await eventsEntry.notifier);
        }
      }
      if (typeof storyID !== 'string') {
        throw new Error(`[${stepName}] selected_story_id must be a string`);
      }
      if ((diaryEvents != null ? diaryEvents.events : void 0) == null) {
        throw new Error(`[${stepName}] diary_events must be an object`);
      }
      kagEntry = M.theLowdown(`kagFor{${storyID}}.json`);
      kag = kagEntry != null ? kagEntry.value : void 0;
      if (kag === void 0) {
        if (typeof (kagEntry != null ? kagEntry.waitFor : void 0) === 'function') {
          kag = (await kagEntry.waitFor());
        } else if ((kagEntry != null ? kagEntry.notifier : void 0) != null) {
          kag = (await kagEntry.notifier);
        }
      }
      if (!Array.isArray(kag != null ? kag.entries : void 0)) {
        throw new Error(`[${stepName}] Missing sqlite KAG ${storyID}`);
      }
      eventWords = new Set();
      ref = diaryEvents.events;
      for (i = 0, len = ref.length; i < len; i++) {
        event = ref[i];
        ref5 = wordSet(`${(ref1 = event != null ? event.kind : void 0) != null ? ref1 : ''} ${(ref2 = event != null ? event.keyword : void 0) != null ? ref2 : ''} ${(ref3 = event != null ? event.headline : void 0) != null ? ref3 : ''} ${(ref4 = event != null ? event.text : void 0) != null ? ref4 : ''}`);
        for (j = 0, len1 = ref5.length; j < len1; j++) {
          word = ref5[j];
          eventWords.add(word);
        }
      }
      scored = [];
      ref6 = kag.entries;
      for (idx = k = 0, len2 = ref6.length; k < len2; idx = ++k) {
        entry = ref6[idx];
        scored.push({
          entry: entry,
          idx: idx,
          score: scoreEntry(entry, eventWords)
        });
      }
      scored.sort(function(a, b) {
        if (b.score !== a.score) {
          return b.score - a.score;
        } else {
          return a.idx - b.idx;
        }
      });
      chosen = (function() {
        var l, len3, ref7, results;
        ref7 = scored.slice(0, Math.min(5, scored.length));
        results = [];
        for (l = 0, len3 = ref7.length; l < len3; l++) {
          row = ref7[l];
          results.push(row.entry);
        }
        return results;
      })();
      keywordSet = new Set();
      keywords = [];
      for (l = 0, len3 = chosen.length; l < len3; l++) {
        entry = chosen[l];
        keyword = String((ref7 = entry != null ? entry.keyword : void 0) != null ? ref7 : '').trim();
        if (!keyword.length) {
          continue;
        }
        if (keywordSet.has(keyword)) {
          continue;
        }
        keywordSet.add(keyword);
        keywords.push(keyword);
      }
      payload = {
        story_id: storyID,
        keywords: keywords,
        entries: chosen
      };
      console.log("[collect_diary_kag_ite] story:", storyID);
      console.log("[collect_diary_kag_ite] chosen KAG entries:", chosen.length);
      M.saveThis('diary_kag', payload);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
