// Generated by CoffeeScript 2.7.0
var buildEventPrompt, callDiaryGenerate, cleanGeneratedText, coerceJSON, describeEvent, eventWordsFor, normalizeDiaryKag, pickEventKagEntries, readArtifactTarget, renderKagLines, renderSourcePassages, resolveEventMatches, resolveMode, resolveRunTag, scoreEntryForEvent, wordSet,
  hasProp = {}.hasOwnProperty;

cleanGeneratedText = function(prompt, rawOutput) {
  var lines, text;
  text = String(rawOutput != null ? rawOutput : '').trim();
  if (!text.length) {
    return '';
  }
  if (text.indexOf(prompt) === 0) {
    text = text.slice(prompt.length).trim();
  }
  lines = text.split(/\r?\n/);
  lines = lines.filter(function(line) {
    var trimmed;
    trimmed = line.trim();
    if (/^=+$/.test(trimmed)) {
      return false;
    }
    if (/^Prompt:\s+\d+\s+tokens/.test(trimmed)) {
      return false;
    }
    if (/^Generation:\s+\d+\s+tokens/.test(trimmed)) {
      return false;
    }
    if (/^Peak memory:\s+/.test(trimmed)) {
      return false;
    }
    return true;
  });
  return lines.join("\n").trim();
};

coerceJSON = function(value) {
  if (typeof value !== 'string') {
    return value;
  }
  try {
    return JSON.parse(value);
  } catch (error) {
    return value;
  }
};

normalizeDiaryKag = function(value) {
  var out, parsedEntries, ref;
  value = coerceJSON(value);
  if (Array.isArray(value != null ? value.entries : void 0)) {
    return value;
  }
  if ((value != null) && typeof value === 'object' && !Array.isArray(value)) {
    if (Array.isArray((ref = value.value) != null ? ref.entries : void 0)) {
      return value.value;
    }
    if (typeof value.entries === 'string') {
      parsedEntries = coerceJSON(value.entries);
      if (Array.isArray(parsedEntries)) {
        out = Object.assign({}, value);
        out.entries = parsedEntries;
        return out;
      }
    }
  }
  return value;
};

resolveEventMatches = function(diaryKag, kind) {
  var matches, ref, row;
  row = diaryKag != null ? (ref = diaryKag.events) != null ? ref[kind] : void 0 : void 0;
  matches = row != null ? row.matches : void 0;
  if (!Array.isArray(matches)) {
    return [];
  }
  return matches;
};

readArtifactTarget = async function(L, artifactKey) {
  var experiment, ref, ref1, ref2, ref3, targetEntry, targetKey, targetValue;
  experiment = (ref = (ref1 = L.theLowdown('experiment.yaml')) != null ? ref1.value : void 0) != null ? ref : {};
  targetKey = experiment != null ? (ref2 = experiment.artifacts) != null ? (ref3 = ref2[artifactKey]) != null ? ref3.target : void 0 : void 0 : void 0;
  if (typeof targetKey !== 'string') {
    return void 0;
  }
  targetEntry = L.theLowdown(targetKey);
  targetValue = targetEntry != null ? targetEntry.value : void 0;
  if (targetValue === void 0) {
    if (typeof (targetEntry != null ? targetEntry.waitFor : void 0) === 'function') {
      targetValue = (await targetEntry.waitFor());
    } else if ((targetEntry != null ? targetEntry.notifier : void 0) != null) {
      targetValue = (await targetEntry.notifier);
    }
  }
  return targetValue;
};

resolveRunTag = function(L) {
  var raw, ref, ref1, ref2, text;
  raw = (ref = (ref1 = process.env.HH_MM) != null ? ref1 : (ref2 = L.theLowdown('env/HH_MM')) != null ? ref2.value : void 0) != null ? ref : null;
  if (raw == null) {
    return null;
  }
  text = String(raw).trim();
  text = text.replace(/^"+|"+$/g, '');
  text = text.replace(/^'+|'+$/g, '');
  if (!text.length) {
    return null;
  }
  return text;
};

wordSet = function(text) {
  var ref, words;
  words = (ref = String(text != null ? text : '').toLowerCase().match(/[a-z0-9]+/g)) != null ? ref : [];
  return new Set(words);
};

scoreEntryForEvent = function(entry, eventWords) {
  var headlineWords, i, keyword, len, ref, ref1, score, word;
  if (!((entry != null) && typeof entry === 'object')) {
    return 0;
  }
  score = 0;
  keyword = String((ref = entry.keyword) != null ? ref : '').trim().toLowerCase();
  headlineWords = wordSet(String((ref1 = entry.headline) != null ? ref1 : ''));
  if (keyword.length && eventWords.has(keyword)) {
    score += 4;
  }
  if (entry.chunk_index != null) {
    score += 2;
  }
  for (i = 0, len = headlineWords.length; i < len; i++) {
    word = headlineWords[i];
    if (eventWords.has(word)) {
      score += 1;
    }
  }
  return score;
};

describeEvent = function(kind, event) {
  var character, lines, location, ref, ref1, ref2, ref3, text, theme;
  if (!((event != null) && typeof event === 'object')) {
    return null;
  }
  text = String((ref = event.text) != null ? ref : '').trim();
  location = String((ref1 = event.location) != null ? ref1 : '').trim();
  character = String((ref2 = event.character) != null ? ref2 : '').trim();
  theme = String((ref3 = event.theme) != null ? ref3 : '').trim();
  lines = [];
  lines.push(`Event kind: ${kind}`);
  if (text.length) {
    lines.push(`Event text: ${text}`);
  }
  if (location.length) {
    lines.push(`Location: ${location}`);
  }
  if (character.length) {
    lines.push(`Character: ${character}`);
  }
  if (theme.length) {
    lines.push(`Theme: ${theme}`);
  }
  if (!lines.length) {
    return null;
  }
  return lines.join("\n");
};

eventWordsFor = function(kind, event) {
  var bits, ref, ref1, ref2, ref3, ref4, ref5;
  bits = [kind, (ref = event != null ? event.text : void 0) != null ? ref : '', (ref1 = event != null ? event.location : void 0) != null ? ref1 : '', (ref2 = event != null ? event.character : void 0) != null ? ref2 : '', (ref3 = event != null ? event.theme : void 0) != null ? ref3 : '', (ref4 = event != null ? event.emotion : void 0) != null ? ref4 : '', ((ref5 = event != null ? event.emotions : void 0) != null ? ref5 : []).join(' ')];
  return wordSet(bits.join(' '));
};

pickEventKagEntries = function(entries, kind, event, limit = 4) {
  var entry, eventWords, i, idx, j, len, len1, ref, ref1, results, row, score, scored;
  eventWords = eventWordsFor(kind, event);
  scored = [];
  ref = entries != null ? entries : [];
  for (idx = i = 0, len = ref.length; i < len; idx = ++i) {
    entry = ref[idx];
    score = scoreEntryForEvent(entry, eventWords);
    if (!(score > 0)) {
      continue;
    }
    scored.push({
      idx: idx,
      score: score,
      entry: entry
    });
  }
  if (scored.length === 0) {
    return (entries != null ? entries : []).slice(0, Math.min(limit, (entries != null ? entries : []).length));
  }
  scored.sort(function(a, b) {
    if (b.score !== a.score) {
      return b.score - a.score;
    } else {
      return a.idx - b.idx;
    }
  });
  ref1 = scored.slice(0, limit);
  results = [];
  for (j = 0, len1 = ref1.length; j < len1; j++) {
    row = ref1[j];
    results.push(row.entry);
  }
  return results;
};

renderKagLines = function(entries) {
  var chunkIndex, entry, headline, i, keyword, label, len, lines, prefix, ref, ref1, ref2;
  lines = [];
  ref = entries != null ? entries : [];
  for (i = 0, len = ref.length; i < len; i++) {
    entry = ref[i];
    keyword = String((ref1 = entry != null ? entry.keyword : void 0) != null ? ref1 : '').trim();
    headline = String((ref2 = entry != null ? entry.headline : void 0) != null ? ref2 : '').trim();
    chunkIndex = entry != null ? entry.chunk_index : void 0;
    label = [];
    if (chunkIndex != null) {
      label.push(`chunk ${chunkIndex}`);
    }
    if (keyword.length) {
      label.push(keyword);
    }
    prefix = label.length ? `- ${label.join(' / ')}` : "- cue";
    if (headline.length) {
      lines.push(`${prefix}: ${headline}`);
    } else {
      lines.push(prefix);
    }
  }
  return lines;
};

renderSourcePassages = function(matches) {
  var chunkIndex, chunkText, headline, i, j, keyword, len, len1, line, lines, match, metaBits, ref, ref1, ref2, ref3, ref4, ref5, storyID;
  lines = [];
  ref = matches != null ? matches : [];
  for (i = 0, len = ref.length; i < len; i++) {
    match = ref[i];
    storyID = String((ref1 = match != null ? match.story_id : void 0) != null ? ref1 : '').trim();
    chunkIndex = match != null ? match.chunk_index : void 0;
    keyword = String((ref2 = match != null ? match.keyword : void 0) != null ? ref2 : '').trim();
    headline = String((ref3 = match != null ? match.headline : void 0) != null ? ref3 : '').trim();
    chunkText = String((ref4 = match != null ? match.chunk_text : void 0) != null ? ref4 : '').trim();
    metaBits = [];
    if (storyID.length) {
      metaBits.push(storyID);
    }
    if (chunkIndex != null) {
      metaBits.push(`chunk ${chunkIndex}`);
    }
    if (keyword.length) {
      metaBits.push(keyword);
    }
    if (headline.length) {
      metaBits.push(headline);
    }
    lines.push(`- ${metaBits.join(' / ')}`);
    if (chunkText.length) {
      ref5 = chunkText.split(/\r?\n/);
      for (j = 0, len1 = ref5.length; j < len1; j++) {
        line = ref5[j];
        lines.push(`  ${line}`);
      }
    }
  }
  return lines;
};

buildEventPrompt = function(storyID, kind, event, chosenEntries, chosenMatches, priorSections, mode) {
  var eventBlock, historyText, kagLines, promptLines, sourceLines, transitionRule;
  eventBlock = describeEvent(kind, event);
  kagLines = renderKagLines(chosenEntries);
  sourceLines = renderSourcePassages(chosenMatches);
  historyText = priorSections.map(function(section) {
    return `${section.kind}:\n${section.text}`;
  }).join("\n\n");
  transitionRule = null;
  if (mode === 'adapter' && priorSections.length > 0) {
    transitionRule = "- Transition naturally from the previous diary section into this event";
  }
  promptLines = ["You are writing in the narrative voice of Jim from St. John's.", "", "Write only the next diary section.", "Do not write the whole diary.", "Stay in first person.", "Use the current event as the focus.", "Use the KAG cues as emotional guidance.", "Preserve continuity with the prior diary sections.", "", "Rules:", "- Keep the narration concrete and grounded", "- Keep the tone observational, slightly humorous, and reflective", "- Do not contradict earlier sections", "- Do not summarize future events", "- Return only the current section prose"];
  if (transitionRule != null) {
    promptLines.push(transitionRule);
  }
  promptLines.push("");
  promptLines.push("Diary story id:");
  promptLines.push(`${storyID}`);
  promptLines.push("");
  promptLines.push("Prior diary history:");
  promptLines.push(historyText.length ? historyText : "- none");
  promptLines.push("");
  promptLines.push("Current event:");
  promptLines.push(eventBlock != null ? eventBlock : "- none");
  promptLines.push("");
  promptLines.push("Current KAG cues:");
  promptLines.push(kagLines.length ? kagLines.join("\n") : "- none");
  promptLines.push("");
  promptLines.push("Raw source passages:");
  promptLines.push(sourceLines.length ? sourceLines.join("\n") : "- none");
  return promptLines.join("\n");
};

resolveMode = function(L) {
  if (/with_adapter/.test(L.stepName)) {
    return {
      mode: 'adapter',
      rawKey: 'diary_adapted_raw',
      metaKey: 'diary_adapted_meta',
      textKey: 'diary_adapted_text',
      fileSuffix: '.adapter.txt'
    };
  }
  if (/without_adapter/.test(L.stepName)) {
    return {
      mode: 'base',
      rawKey: 'diary_base_raw',
      metaKey: 'diary_base_meta',
      textKey: 'diary_base_text',
      fileSuffix: '.txt'
    };
  }
  throw new Error(`[${L.stepName}] event ordered diary generator expects a with_adapter or without_adapter step name`);
};

callDiaryGenerate = function(L, modelDir, prompt, adapterPath, mlxConfig) {
  var args, key, value;
  args = {
    model: modelDir,
    prompt: prompt
  };
  if (adapterPath != null) {
    args["adapter-path"] = adapterPath;
  }
  if ((mlxConfig != null) && typeof mlxConfig === 'object' && !Array.isArray(mlxConfig)) {
    for (key in mlxConfig) {
      if (!hasProp.call(mlxConfig, key)) continue;
      value = mlxConfig[key];
      if (value == null) {
        continue;
      }
      args[key] = value;
    }
  }
  return L.callMLX('generate', args);
};

this.step = {
  desc: "Generate a diary entry one event at a time in story order",
  action: async function(L) {
    var adapterPath, chosenEntries, chosenMatches, diaryKag, entry, event, eventOrder, finalText, i, kind, len, meta, mlxConfig, modeInfo, modelDir, priorSections, prompt, rawJoined, rawOutput, rawSections, ref, ref1, runTag, sectionText, storyID, storyParts;
    modeInfo = resolveMode(L);
    storyParts = (await L.need('story_parts'));
    storyParts = coerceJSON(storyParts);
    if (!((storyParts != null) && typeof storyParts === 'object' && !Array.isArray(storyParts))) {
      storyParts = (await readArtifactTarget(L, 'story_parts'));
      storyParts = coerceJSON(storyParts);
    }
    if (!((storyParts != null) && typeof storyParts === 'object' && !Array.isArray(storyParts))) {
      throw new Error(`[${L.stepName}] story_parts must be an object`);
    }
    diaryKag = (ref = L.theLowdown('diary_kag')) != null ? ref.value : void 0;
    if (!Array.isArray(diaryKag != null ? diaryKag.entries : void 0)) {
      diaryKag = (await readArtifactTarget(L, 'diary_kag'));
    }
    diaryKag = normalizeDiaryKag(diaryKag);
    if (!Array.isArray(diaryKag != null ? diaryKag.entries : void 0)) {
      throw new Error(`[${L.stepName}] diary_kag must be an object with entries`);
    }
    storyID = String((ref1 = storyParts.story_id) != null ? ref1 : '').trim();
    modelDir = L.param('quantized_model_dir', null);
    adapterPath = L.param('adapter_path', null);
    mlxConfig = L.param('mlx', null);
    if (modelDir == null) {
      throw new Error(`[${L.stepName}] Missing quantized_model_dir param`);
    }
    if (modeInfo.mode === 'adapter' && (adapterPath == null)) {
      throw new Error(`[${L.stepName}] Missing adapter_path`);
    }
    if ((mlxConfig != null) && (typeof mlxConfig !== 'object' || Array.isArray(mlxConfig))) {
      throw new Error(`[${L.stepName}] mlx must be an object when provided`);
    }
    eventOrder = [['scene', storyParts.scene], ['arrival', storyParts.arrival], ['disturbance', storyParts.disturbance], ['reflection', storyParts.reflection], ['realization', storyParts.realization]];
    priorSections = [];
    rawSections = [];
    for (i = 0, len = eventOrder.length; i < len; i++) {
      [kind, event] = eventOrder[i];
      if (!((event != null) && typeof event === 'object')) {
        continue;
      }
      chosenMatches = resolveEventMatches(diaryKag, kind);
      chosenEntries = chosenMatches.length > 0 ? chosenMatches : pickEventKagEntries(diaryKag.entries, kind, event, 4);
      prompt = buildEventPrompt(storyID, kind, event, chosenEntries, chosenMatches, priorSections, modeInfo.mode);
      rawOutput = callDiaryGenerate(L, modelDir, prompt, adapterPath, mlxConfig);
      sectionText = cleanGeneratedText(prompt, rawOutput);
      if (!sectionText.length) {
        continue;
      }
      rawSections.push({
        kind: kind,
        prompt: prompt,
        raw: String(rawOutput != null ? rawOutput : ''),
        text: sectionText,
        chunk_indexes: (function() {
          var j, len1, results;
          results = [];
          for (j = 0, len1 = chosenEntries.length; j < len1; j++) {
            entry = chosenEntries[j];
            if ((entry != null ? entry.chunk_index : void 0) != null) {
              results.push(entry.chunk_index);
            }
          }
          return results;
        })(),
        keywords: (function() {
          var j, len1, ref2, ref3, results;
          results = [];
          for (j = 0, len1 = chosenEntries.length; j < len1; j++) {
            entry = chosenEntries[j];
            if (String((ref2 = entry != null ? entry.keyword : void 0) != null ? ref2 : '').trim().length) {
              results.push(String((ref3 = entry.keyword) != null ? ref3 : '').trim());
            }
          }
          return results;
        })()
      });
      priorSections.push({
        kind: kind,
        text: sectionText
      });
      console.log(`[${L.stepName}] generated section ${kind} chars:`, sectionText.length);
    }
    finalText = priorSections.map(function(section) {
      return section.text;
    }).join("\n\n");
    rawJoined = rawSections.map(function(section) {
      return `[${section.kind}]\n${section.raw}`;
    }).join("\n\n==========\n\n");
    meta = {
      story_id: storyID,
      mode: modeInfo.mode,
      model_dir: modelDir,
      adapter_path: modeInfo.mode === 'adapter' ? adapterPath : null,
      section_count: priorSections.length,
      sections: rawSections.map(function(section) {
        return {
          kind: section.kind,
          text_chars: section.text.length,
          chunk_indexes: section.chunk_indexes,
          keywords: section.keywords
        };
      }),
      raw_chars: rawJoined.length,
      text_chars: finalText.length
    };
    console.log(`[${L.stepName}] story:`, storyID);
    console.log(`[${L.stepName}] section count:`, priorSections.length);
    console.log(`[${L.stepName}] text chars:`, finalText.length);
    L.make(modeInfo.rawKey, rawJoined);
    L.make(modeInfo.metaKey, meta);
    L.make(modeInfo.textKey, finalText);
    runTag = resolveRunTag(L);
    if (typeof runTag === 'string' && runTag.length) {
      L.saveThis(`diary/diary_${runTag}${modeInfo.fileSuffix}`, finalText);
    }
    L.done();
  }
};
