// Generated by CoffeeScript 2.7.0
(function() {
  var cleanGeneratedText;

  cleanGeneratedText = function(prompt, rawOutput) {
    var lines, text;
    text = String(rawOutput != null ? rawOutput : '').trim();
    if (!text.length) {
      return '';
    }
    if (text.indexOf(prompt) === 0) {
      text = text.slice(prompt.length).trim();
    }
    lines = text.split(/\r?\n/);
    lines = lines.filter(function(line) {
      var trimmed;
      trimmed = line.trim();
      if (/^Prompt:\s+\d+\s+tokens/.test(trimmed)) {
        return false;
      }
      if (/^Generation:\s+\d+\s+tokens/.test(trimmed)) {
        return false;
      }
      if (/^Peak memory:\s+/.test(trimmed)) {
        return false;
      }
      return true;
    });
    return lines.join("\n").trim();
  };

  this.step = {
    desc: "Generate a diary entry without the adapter",
    action: async function(M, stepName) {
      var explicitModelDir, meta, modelDir, modelMemoKey, prompt, promptEntry, rawOutput, ref, ref1, ref2, storyID, storyIDEntry, text;
      storyIDEntry = M.theLowdown('selected_story_id');
      storyID = storyIDEntry != null ? storyIDEntry.value : void 0;
      if (storyID === void 0) {
        if (typeof (storyIDEntry != null ? storyIDEntry.waitFor : void 0) === 'function') {
          storyID = (await storyIDEntry.waitFor());
        } else if ((storyIDEntry != null ? storyIDEntry.notifier : void 0) != null) {
          storyID = (await storyIDEntry.notifier);
        }
      }
      promptEntry = M.theLowdown('diary_prompt_text');
      prompt = promptEntry != null ? promptEntry.value : void 0;
      if (prompt === void 0) {
        if (typeof (promptEntry != null ? promptEntry.waitFor : void 0) === 'function') {
          prompt = (await promptEntry.waitFor());
        } else if ((promptEntry != null ? promptEntry.notifier : void 0) != null) {
          prompt = (await promptEntry.notifier);
        }
      }
      if (typeof storyID !== 'string') {
        throw new Error(`[${stepName}] selected_story_id must be a string`);
      }
      if (typeof prompt !== 'string') {
        throw new Error(`[${stepName}] diary_prompt_text must be a string`);
      }
      modelMemoKey = M.getStepParam(stepName, 'model_memo_key');
      if (modelMemoKey === void 0) {
        modelMemoKey = 'modelDir';
      }
      explicitModelDir = M.getStepParam(stepName, 'model_dir');
      modelDir = (ref = explicitModelDir != null ? explicitModelDir : (ref1 = M.theLowdown(modelMemoKey)) != null ? ref1.value : void 0) != null ? ref : (ref2 = M.theLowdown('modelDir')) != null ? ref2.value : void 0;
      if (modelDir == null) {
        throw new Error(`[${stepName}] Missing modelDir in memo`);
      }
      rawOutput = M.callMLX('generate', {
        model: modelDir,
        prompt: prompt
      }, M.getStepParam(stepName, 'debug_mlx') === true);
      text = cleanGeneratedText(prompt, rawOutput);
      meta = {
        story_id: storyID,
        mode: 'base',
        model_dir: modelDir,
        adapter_path: null,
        raw_chars: String(rawOutput != null ? rawOutput : '').length,
        text_chars: text.length
      };
      console.log("[generate_diary_without_adapter_ite] story:", storyID);
      console.log("[generate_diary_without_adapter_ite] text chars:", text.length);
      M.saveThis('diary_base_raw', String(rawOutput != null ? rawOutput : ''));
      M.saveThis('diary_base_meta', meta);
      M.saveThis('diary_base_text', text);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
