// Generated by CoffeeScript 2.7.0
(function() {
  var eventTextFor;

  eventTextFor = function(storyTitle, entry, idx) {
    var fallback, headline, keyword, ref, ref1;
    headline = String((ref = entry != null ? entry.headline : void 0) != null ? ref : '').trim();
    keyword = String((ref1 = entry != null ? entry.keyword : void 0) != null ? ref1 : '').trim();
    fallback = (function() {
      switch (idx) {
        case 0:
          return `the day around ${storyTitle} already felt slightly off`;
        case 1:
          return "someone or something arrived and shifted the mood";
        case 2:
          return "the quiet shape of the day gave way to trouble";
        case 3:
          return "I kept turning the moment over in my head";
        default:
          return "something about the day finally became clear";
      }
    })();
    if (!(headline.length || keyword.length)) {
      return fallback;
    }
    if (headline.length && keyword.length) {
      return `${headline} while ${keyword} stayed close to everything`;
    }
    if (headline.length) {
      return headline;
    }
    return `${storyTitle} felt marked by ${keyword}`;
  };

  this.step = {
    desc: "Select a story and derive diary events from its SQLite-backed KAG",
    action: async function(M, stepName) {
      var entry, events, i, idx, kag, kagEntry, keyword, kind, kinds, len, payload, ref, ref1, ref2, ref3, story, storyEntry, storyID, storyTitle;
      storyID = M.getStepParam(stepName, 'story_id');
      if (storyID == null) {
        throw new Error(`[${stepName}] Missing required param 'story_id'`);
      }
      storyEntry = M.theLowdown(`storyByID{${storyID}}.json`);
      story = storyEntry != null ? storyEntry.value : void 0;
      if (story === void 0) {
        if (typeof (storyEntry != null ? storyEntry.waitFor : void 0) === 'function') {
          story = (await storyEntry.waitFor());
        } else if ((storyEntry != null ? storyEntry.notifier : void 0) != null) {
          story = (await storyEntry.notifier);
        }
      }
      kagEntry = M.theLowdown(`kagFor{${storyID}}.json`);
      kag = kagEntry != null ? kagEntry.value : void 0;
      if (kag === void 0) {
        if (typeof (kagEntry != null ? kagEntry.waitFor : void 0) === 'function') {
          kag = (await kagEntry.waitFor());
        } else if ((kagEntry != null ? kagEntry.notifier : void 0) != null) {
          kag = (await kagEntry.notifier);
        }
      }
      if ((story != null ? story.text : void 0) == null) {
        throw new Error(`[${stepName}] Missing sqlite story ${storyID}`);
      }
      if (!(Array.isArray(kag != null ? kag.entries : void 0) && kag.entries.length > 0)) {
        throw new Error(`[${stepName}] Missing sqlite KAG ${storyID}`);
      }
      storyTitle = String((ref = story.title) != null ? ref : storyID).trim();
      kinds = ['scene', 'arrival', 'disturbance', 'reflection', 'realization'];
      events = [];
      for (idx = i = 0, len = kinds.length; i < len; idx = ++i) {
        kind = kinds[idx];
        entry = (ref1 = kag.entries[idx]) != null ? ref1 : kag.entries[kag.entries.length - 1];
        events.push({
          kind: kind,
          keyword: String((ref2 = entry != null ? entry.keyword : void 0) != null ? ref2 : '').trim(),
          headline: String((ref3 = entry != null ? entry.headline : void 0) != null ? ref3 : '').trim(),
          text: eventTextFor(storyTitle, entry, idx)
        });
      }
      payload = {
        story_id: storyID,
        title: storyTitle,
        events: events,
        source_keywords: (function() {
          var j, len1, ref4, ref5, results;
          ref5 = (ref4 = kag.keywords) != null ? ref4 : [];
          results = [];
          for (j = 0, len1 = ref5.length; j < len1; j++) {
            keyword = ref5[j];
            if (String(keyword != null ? keyword : '').trim().length > 0) {
              results.push(String(keyword != null ? keyword : '').trim());
            }
          }
          return results;
        })()
      };
      console.log("[select_diary_events_ite] story:", storyID);
      console.log("[select_diary_events_ite] event count:", events.length);
      M.saveThis('selected_story_id', storyID);
      M.saveThis('diary_events', payload);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
