// Generated by CoffeeScript 2.7.0
(function() {
  // meta/sqlite.coffee
  var DatabaseSync, path;

  path = require('path');

  ({DatabaseSync} = require('node:sqlite'));

  module.exports = function(M, opts = {}) {
    var FORMATTERS, REQUESTS, baseDir, db, dbFile, dbPath, debugEnabled, debugLog, ref, ref1;
    baseDir = (ref = opts.baseDir) != null ? ref : process.cwd();
    dbFile = (ref1 = opts.sqliteFile) != null ? ref1 : 'runtime.sqlite';
    dbPath = path.isAbsolute(dbFile) ? dbFile : path.join(baseDir, dbFile);
    db = new DatabaseSync(dbPath);
    debugEnabled = function() {
      var globalParams, ref2, ref3;
      try {
        globalParams = (ref2 = (ref3 = M.theLowdown("params/_global.yaml")) != null ? ref3.value : void 0) != null ? ref2 : {};
        return globalParams.debug_sql === true;
      } catch (error) {
        return false;
      }
    };
    debugLog = function(...parts) {
      if (!debugEnabled()) {
        return;
      }
      return console.log(`[${new Date().toISOString()}] [SQL]`, ...parts);
    };
    // HEY JIM! There is no repo-defined SQLite schema yet, so this file
    // creates the minimum schema needed for the request-key contract.
    db.exec(`CREATE TABLE IF NOT EXISTS stories (
  story_id TEXT PRIMARY KEY,
  title TEXT,
  text TEXT
);

CREATE TABLE IF NOT EXISTS story_parts (
  story_id TEXT PRIMARY KEY,
  scene TEXT,
  arrival TEXT,
  disturbance TEXT,
  reflection TEXT,
  realization TEXT
);

CREATE TABLE IF NOT EXISTS expanded_story_parts (
  story_id TEXT PRIMARY KEY,
  scene_json TEXT,
  arrival_json TEXT,
  disturbance_json TEXT,
  reflection_json TEXT,
  realization_json TEXT
);

CREATE TABLE IF NOT EXISTS kag_entries (
  story_id TEXT NOT NULL,
  entry_index INTEGER NOT NULL,
  doc_id TEXT,
  paragraph_index TEXT,
  keyword TEXT,
  headline TEXT,
  entry_json TEXT,
  PRIMARY KEY (story_id, entry_index)
);

CREATE INDEX IF NOT EXISTS idx_kag_entries_story_id
  ON kag_entries (story_id);

CREATE INDEX IF NOT EXISTS idx_kag_entries_keyword
  ON kag_entries (keyword);

CREATE TABLE IF NOT EXISTS lora_trained_stories (
  story_id TEXT PRIMARY KEY,
  trained_at TEXT
);

CREATE TABLE IF NOT EXISTS lora_story_usage (
  story_id TEXT PRIMARY KEY,
  use_count INTEGER NOT NULL DEFAULT 0,
  last_trained_at TEXT,
  last_run_id TEXT
);

CREATE TABLE IF NOT EXISTS lora_training_runs (
  run_id TEXT PRIMARY KEY,
  started_at TEXT,
  finished_at TEXT,
  status TEXT,
  model_dir TEXT,
  adapter_path TEXT,
  resume_adapter_file TEXT,
  training_dir TEXT,
  stdout_text TEXT,
  train_rows_count INTEGER,
  valid_rows_count INTEGER,
  test_rows_count INTEGER,
  checkpoint_path TEXT
);

CREATE TABLE IF NOT EXISTS lora_training_run_stories (
  run_id TEXT NOT NULL,
  story_id TEXT NOT NULL,
  PRIMARY KEY (run_id, story_id)
);`);
    FORMATTERS = {
      json: {
        read: function(value) {
          if (!((value != null) && typeof value === 'object' && !Array.isArray(value))) {
            throw new Error("sqlite meta expected object for .json");
          }
          return value;
        },
        write: function(value) {
          if (!((value != null) && typeof value === 'object' && !Array.isArray(value))) {
            throw new Error("sqlite meta expected object for .json");
          }
          return value;
        }
      },
      jsonl: {
        read: function(value) {
          if (!Array.isArray(value)) {
            throw new Error("sqlite meta expected array for .jsonl");
          }
          return value;
        },
        write: function(value) {
          if (!Array.isArray(value)) {
            throw new Error("sqlite meta expected array for .jsonl");
          }
          return value;
        }
      },
      txt: {
        read: function(value) {
          if (typeof value === 'string') {
            return value;
          } else {
            // HEY JIM! The directive requires txt support but does not define
            // a canonical text projection for structured values.
            return JSON.stringify(value, null, 2);
          }
        },
        write: function(value) {
          if (typeof value === 'string') {
            return value;
          } else {
            return JSON.stringify(value, null, 2);
          }
        }
      },
      csv: {
        read: function(value) {
          if (Array.isArray(value)) {
            return value;
          } else if ((value != null) && typeof value === 'object') {
            return value;
          } else {
            throw new Error("sqlite meta expected object or array for .csv");
          }
        },
        write: function(value) {
          if (Array.isArray(value)) {
            return value;
          } else if ((value != null) && typeof value === 'object') {
            return value;
          } else {
            throw new Error("sqlite meta expected object or array for .csv");
          }
        }
      }
    };
    REQUESTS = [
      {
        name: 'storyByID',
        regex: /^storyByID\{([^}]+)\}$/,
        allowedSuffixes: ['json',
      'txt',
      'csv'],
        read: function(db,
      storyID) {
          var row;
          row = db.prepare(`SELECT story_id, title, text
FROM stories
WHERE story_id = ?`).get(storyID);
          if (row == null) {
            throw new Error(`sqlite meta missing storyByID ${storyID}`);
          }
          return {
            story_id: row.story_id,
            title: row.title,
            text: row.text
          };
        },
        write: function(db,
      value,
      storyID) {
          var ref2,
      ref3,
      ref4,
      ref5,
      ref6,
      writeStoryID;
          if (!((value != null) && typeof value === 'object' && !Array.isArray(value))) {
            throw new Error("sqlite meta storyByID write expects object");
          }
          writeStoryID = (ref2 = value.story_id) != null ? ref2 : storyID;
          if (writeStoryID !== storyID) {
            throw new Error("sqlite meta storyByID story_id mismatch");
          }
          db.prepare(`INSERT INTO stories (story_id, title, text)
VALUES (?, ?, ?)
ON CONFLICT(story_id) DO UPDATE SET
  title = excluded.title,
  text = excluded.text`).run(writeStoryID,
      (ref3 = value.title) != null ? ref3 : null,
      (ref4 = value.text) != null ? ref4 : null);
          return {
            story_id: writeStoryID,
            title: (ref5 = value.title) != null ? ref5 : null,
            text: (ref6 = value.text) != null ? ref6 : null
          };
        }
      },
      {
        name: 'partsFor',
        regex: /^partsFor\{([^}]+)\}$/,
        allowedSuffixes: ['json',
      'txt',
      'csv'],
        read: function(db,
      storyID) {
          var row;
          row = db.prepare(`SELECT story_id, scene, arrival, disturbance, reflection, realization
FROM story_parts
WHERE story_id = ?`).get(storyID);
          if (row == null) {
            throw new Error(`sqlite meta missing partsFor ${storyID}`);
          }
          return {
            story_id: row.story_id,
            parts: {
              scene: row.scene,
              arrival: row.arrival,
              disturbance: row.disturbance,
              reflection: row.reflection,
              realization: row.realization
            }
          };
        },
        write: function(db,
      value,
      storyID) {
          var ref10,
      ref11,
      ref12,
      ref2,
      ref3,
      ref4,
      ref5,
      ref6,
      ref7,
      ref8,
      ref9,
      writeStoryID;
          if (!((value != null) && typeof value === 'object' && !Array.isArray(value))) {
            throw new Error("sqlite meta partsFor write expects object");
          }
          if (!((value.parts != null) && typeof value.parts === 'object' && !Array.isArray(value.parts))) {
            throw new Error("sqlite meta partsFor write expects value.parts");
          }
          writeStoryID = (ref2 = value.story_id) != null ? ref2 : storyID;
          if (writeStoryID !== storyID) {
            throw new Error("sqlite meta partsFor story_id mismatch");
          }
          db.prepare(`INSERT INTO story_parts (
  story_id, scene, arrival, disturbance, reflection, realization
)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(story_id) DO UPDATE SET
  scene = excluded.scene,
  arrival = excluded.arrival,
  disturbance = excluded.disturbance,
  reflection = excluded.reflection,
  realization = excluded.realization`).run(writeStoryID,
      (ref3 = value.parts.scene) != null ? ref3 : null,
      (ref4 = value.parts.arrival) != null ? ref4 : null,
      (ref5 = value.parts.disturbance) != null ? ref5 : null,
      (ref6 = value.parts.reflection) != null ? ref6 : null,
      (ref7 = value.parts.realization) != null ? ref7 : null);
          return {
            story_id: writeStoryID,
            parts: {
              scene: (ref8 = value.parts.scene) != null ? ref8 : null,
              arrival: (ref9 = value.parts.arrival) != null ? ref9 : null,
              disturbance: (ref10 = value.parts.disturbance) != null ? ref10 : null,
              reflection: (ref11 = value.parts.reflection) != null ? ref11 : null,
              realization: (ref12 = value.parts.realization) != null ? ref12 : null
            }
          };
        }
      },
      {
        name: 'kagFor',
        regex: /^kagFor\{([^}]+)\}$/,
        allowedSuffixes: ['json',
      'txt',
      'csv'],
        read: function(db,
      storyID) {
          var entries,
      entry,
      i,
      keyword,
      keywords,
      len,
      row,
      rows,
      seenKeywords;
          rows = db.prepare(`SELECT story_id, entry_index, doc_id, paragraph_index, keyword, headline, entry_json
FROM kag_entries
WHERE story_id = ?
ORDER BY entry_index ASC`).all(storyID);
          if (!rows.length) {
            throw new Error(`sqlite meta missing kagFor ${storyID}`);
          }
          entries = [];
          seenKeywords = new Set();
          keywords = [];
          for (i = 0, len = rows.length; i < len; i++) {
            row = rows[i];
            entry = null;
            if (row.entry_json != null) {
              entry = JSON.parse(row.entry_json);
            } else {
              entry = {
                story_id: row.story_id,
                entry_index: row.entry_index,
                doc_id: row.doc_id,
                paragraph_index: row.paragraph_index,
                keyword: row.keyword,
                headline: row.headline
              };
            }
            entries.push(entry);
            keyword = row.keyword;
            if ((keyword != null) && !seenKeywords.has(keyword)) {
              seenKeywords.add(keyword);
              keywords.push(keyword);
            }
          }
          return {
            story_id: storyID,
            entries: entries,
            keywords: keywords
          };
        },
        write: function(db,
      value,
      storyID) {
          var docID,
      entry,
      entryIndex,
      err,
      headline,
      i,
      insertStatement,
      keyword,
      len,
      paragraphIndex,
      ref10,
      ref11,
      ref12,
      ref13,
      ref2,
      ref3,
      ref4,
      ref5,
      ref6,
      ref7,
      ref8,
      ref9,
      writeStoryID;
          if (!((value != null) && typeof value === 'object' && !Array.isArray(value))) {
            throw new Error("sqlite meta kagFor write expects object");
          }
          if (!Array.isArray(value.entries)) {
            throw new Error("sqlite meta kagFor write expects entries array");
          }
          if (!Array.isArray(value.keywords)) {
            throw new Error("sqlite meta kagFor write expects keywords array");
          }
          writeStoryID = (ref2 = value.story_id) != null ? ref2 : storyID;
          if (writeStoryID !== storyID) {
            throw new Error("sqlite meta kagFor story_id mismatch");
          }
          // HEY JIM! Queryable KAG keywords are stored per entry row. Keywords
          // present only in value.keywords but not attached to an entry are not
          // independently queryable because the prompt did not define a separate
          // storage shape for them.
          db.exec('BEGIN');
          try {
            db.prepare(`DELETE FROM kag_entries
WHERE story_id = ?`).run(writeStoryID);
            insertStatement = db.prepare(`INSERT INTO kag_entries (
  story_id, entry_index, doc_id, paragraph_index, keyword, headline, entry_json
)
VALUES (?, ?, ?, ?, ?, ?, ?)`);
            entryIndex = 1;
            ref3 = value.entries;
            for (i = 0, len = ref3.length; i < len; i++) {
              entry = ref3[i];
              docID = (ref4 = (ref5 = entry != null ? entry.doc_id : void 0) != null ? ref5 : entry != null ? (ref6 = entry.meta) != null ? ref6.doc_id : void 0 : void 0) != null ? ref4 : null;
              paragraphIndex = (ref7 = (ref8 = entry != null ? entry.paragraph_index : void 0) != null ? ref8 : entry != null ? (ref9 = entry.meta) != null ? ref9.paragraph_index : void 0 : void 0) != null ? ref7 : null;
              keyword = (ref10 = entry != null ? entry.keyword : void 0) != null ? ref10 : null;
              headline = (ref11 = (ref12 = (ref13 = entry != null ? entry.headline : void 0) != null ? ref13 : entry != null ? entry.label : void 0) != null ? ref12 : entry != null ? entry.text : void 0) != null ? ref11 : null;
              insertStatement.run(writeStoryID,
      entryIndex,
      docID,
      paragraphIndex,
      keyword,
      headline,
      JSON.stringify(entry));
              entryIndex += 1;
            }
            db.exec('COMMIT');
          } catch (error) {
            err = error;
            try {
              db.exec('ROLLBACK');
            } catch (error) {
              null;
            }
            throw err;
          }
          return {
            story_id: writeStoryID,
            entries: value.entries,
            keywords: value.keywords
          };
        }
      },
      {
        name: 'expandedPartsFor',
        regex: /^expandedPartsFor\{([^}]+)\}$/,
        allowedSuffixes: ['json',
      'txt',
      'csv'],
        read: function(db,
      storyID) {
          var parsePart,
      row;
          row = db.prepare(`SELECT story_id, scene_json, arrival_json, disturbance_json, reflection_json, realization_json
FROM expanded_story_parts
WHERE story_id = ?`).get(storyID);
          if (row == null) {
            throw new Error(`sqlite meta missing expandedPartsFor ${storyID}`);
          }
          parsePart = function(raw) {
            if (raw == null) {
              return null;
            }
            return JSON.parse(raw);
          };
          return {
            story_id: row.story_id,
            expanded_parts: {
              scene: parsePart(row.scene_json),
              arrival: parsePart(row.arrival_json),
              disturbance: parsePart(row.disturbance_json),
              reflection: parsePart(row.reflection_json),
              realization: parsePart(row.realization_json)
            }
          };
        },
        write: function(db,
      value,
      storyID) {
          var ref2,
      ref3,
      ref4,
      ref5,
      ref6,
      ref7,
      writeStoryID;
          if (!((value != null) && typeof value === 'object' && !Array.isArray(value))) {
            throw new Error("sqlite meta expandedPartsFor write expects object");
          }
          if (!((value.expanded_parts != null) && typeof value.expanded_parts === 'object' && !Array.isArray(value.expanded_parts))) {
            throw new Error("sqlite meta expandedPartsFor write expects expanded_parts");
          }
          writeStoryID = (ref2 = value.story_id) != null ? ref2 : storyID;
          if (writeStoryID !== storyID) {
            throw new Error("sqlite meta expandedPartsFor story_id mismatch");
          }
          db.prepare(`INSERT INTO expanded_story_parts (
  story_id, scene_json, arrival_json, disturbance_json, reflection_json, realization_json
)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(story_id) DO UPDATE SET
  scene_json = excluded.scene_json,
  arrival_json = excluded.arrival_json,
  disturbance_json = excluded.disturbance_json,
  reflection_json = excluded.reflection_json,
  realization_json = excluded.realization_json`).run(writeStoryID,
      JSON.stringify((ref3 = value.expanded_parts.scene) != null ? ref3 : null),
      JSON.stringify((ref4 = value.expanded_parts.arrival) != null ? ref4 : null),
      JSON.stringify((ref5 = value.expanded_parts.disturbance) != null ? ref5 : null),
      JSON.stringify((ref6 = value.expanded_parts.reflection) != null ? ref6 : null),
      JSON.stringify((ref7 = value.expanded_parts.realization) != null ? ref7 : null));
          return {
            story_id: writeStoryID,
            expanded_parts: value.expanded_parts
          };
        }
      },
      {
        name: 'storiesWithKag',
        regex: /^storiesWithKag\{([^}]+)\}$/,
        allowedSuffixes: ['jsonl',
      'txt',
      'csv'],
        read: function(db,
      keyword) {
          return db.prepare(`SELECT DISTINCT stories.story_id, stories.title, stories.text
FROM stories
INNER JOIN kag_entries
  ON kag_entries.story_id = stories.story_id
WHERE kag_entries.keyword = ?
ORDER BY stories.story_id ASC`).all(keyword);
        },
        write: null
      },
      {
        name: 'storiesMissingKag',
        regex: /^storiesMissingKag$/,
        allowedSuffixes: ['jsonl',
      'txt',
      'csv'],
        read: function(db) {
          return db.prepare(`SELECT stories.story_id, stories.title, stories.text
FROM stories
WHERE NOT EXISTS (
  SELECT 1
  FROM kag_entries
  WHERE kag_entries.story_id = stories.story_id
)
ORDER BY stories.story_id ASC`).all();
        },
        write: null
      },
      {
        name: 'allStories',
        regex: /^allStories$/,
        allowedSuffixes: ['jsonl',
      'txt',
      'csv'],
        read: function(db) {
          return db.prepare(`SELECT story_id, title, text
FROM stories
ORDER BY story_id ASC`).all();
        },
        write: null
      },
      {
        name: 'trainedStories',
        regex: /^trainedStories$/,
        allowedSuffixes: ['jsonl',
      'txt',
      'csv'],
        read: function(db) {
          return db.prepare(`SELECT story_id, trained_at
FROM lora_trained_stories
ORDER BY story_id ASC`).all();
        },
        write: function(db,
      value) {
          var err,
      i,
      insertStatement,
      j,
      len,
      len1,
      ref2,
      ref3,
      row,
      rows,
      storyID,
      trainedAt;
          if (!Array.isArray(value)) {
            throw new Error("sqlite meta trainedStories write expects array");
          }
          db.exec('BEGIN');
          try {
            db.exec("DELETE FROM lora_trained_stories");
            insertStatement = db.prepare(`INSERT INTO lora_trained_stories (story_id, trained_at)
VALUES (?, ?)`);
            for (i = 0, len = value.length; i < len; i++) {
              row = value[i];
              if (typeof row === 'string') {
                storyID = row;
                trainedAt = null;
              } else {
                if (!((row != null) && typeof row === 'object' && !Array.isArray(row))) {
                  throw new Error("sqlite meta trainedStories write expects objects or strings");
                }
                storyID = row.story_id;
                trainedAt = (ref2 = row.trained_at) != null ? ref2 : null;
              }
              if (storyID == null) {
                throw new Error("sqlite meta trainedStories write missing story_id");
              }
              insertStatement.run(storyID,
      trainedAt);
            }
            db.exec('COMMIT');
          } catch (error) {
            err = error;
            try {
              db.exec('ROLLBACK');
            } catch (error) {
              null;
            }
            throw err;
          }
          rows = [];
          for (j = 0, len1 = value.length; j < len1; j++) {
            row = value[j];
            if (typeof row === 'string') {
              rows.push({
                story_id: row,
                trained_at: null
              });
            } else {
              rows.push({
                story_id: row.story_id,
                trained_at: (ref3 = row.trained_at) != null ? ref3 : null
              });
            }
          }
          return rows;
        }
      },
      {
        name: 'loraStoryUsage',
        regex: /^loraStoryUsage$/,
        allowedSuffixes: ['jsonl',
      'txt',
      'csv'],
        read: function(db) {
          return db.prepare(`SELECT
  stories.story_id,
  stories.title,
  COALESCE(lora_story_usage.use_count, 0) AS use_count,
  lora_story_usage.last_trained_at,
  lora_story_usage.last_run_id
FROM stories
LEFT JOIN lora_story_usage
  ON lora_story_usage.story_id = stories.story_id
ORDER BY COALESCE(lora_story_usage.use_count, 0) ASC, stories.story_id ASC`).all();
        },
        write: null
      },
      {
        name: 'loraTrainingRun',
        regex: /^loraTrainingRun\{([^}]+)\}$/,
        allowedSuffixes: ['json',
      'txt',
      'csv'],
        read: function(db,
      runID) {
          var row,
      storyRow,
      storyRows;
          row = db.prepare(`SELECT
  run_id,
  started_at,
  finished_at,
  status,
  model_dir,
  adapter_path,
  resume_adapter_file,
  training_dir,
  stdout_text,
  train_rows_count,
  valid_rows_count,
  test_rows_count,
  checkpoint_path
FROM lora_training_runs
WHERE run_id = ?`).get(runID);
          if (row == null) {
            throw new Error(`sqlite meta missing loraTrainingRun ${runID}`);
          }
          storyRows = db.prepare(`SELECT story_id
FROM lora_training_run_stories
WHERE run_id = ?
ORDER BY story_id ASC`).all(runID);
          return {
            run_id: row.run_id,
            started_at: row.started_at,
            finished_at: row.finished_at,
            status: row.status,
            model_dir: row.model_dir,
            adapter_path: row.adapter_path,
            resume_adapter_file: row.resume_adapter_file,
            training_dir: row.training_dir,
            stdout_text: row.stdout_text,
            train_rows_count: row.train_rows_count,
            valid_rows_count: row.valid_rows_count,
            test_rows_count: row.test_rows_count,
            checkpoint_path: row.checkpoint_path,
            story_ids: (function() {
              var i,
      len,
      results;
              results = [];
              for (i = 0, len = storyRows.length; i < len; i++) {
                storyRow = storyRows[i];
                results.push(storyRow.story_id);
              }
              return results;
            })()
          };
        },
        write: function(db,
      value,
      runID) {
          var adapterPath,
      checkpointPath,
      err,
      finishedAt,
      i,
      insertStory,
      len,
      modelDir,
      ref10,
      ref11,
      ref12,
      ref13,
      ref14,
      ref15,
      ref2,
      ref3,
      ref4,
      ref5,
      ref6,
      ref7,
      ref8,
      ref9,
      resumeAdapterFile,
      startedAt,
      status,
      stdoutText,
      storyID,
      testRowsCount,
      trainRowsCount,
      trainingDir,
      validRowsCount,
      writeRunID;
          if (!((value != null) && typeof value === 'object' && !Array.isArray(value))) {
            throw new Error("sqlite meta loraTrainingRun write expects object");
          }
          writeRunID = (ref2 = value.run_id) != null ? ref2 : runID;
          if (writeRunID !== runID) {
            throw new Error("sqlite meta loraTrainingRun run_id mismatch");
          }
          if (!Array.isArray(value.story_ids)) {
            throw new Error("sqlite meta loraTrainingRun write expects story_ids array");
          }
          startedAt = (ref3 = value.started_at) != null ? ref3 : null;
          finishedAt = (ref4 = value.finished_at) != null ? ref4 : null;
          status = (ref5 = value.status) != null ? ref5 : null;
          modelDir = (ref6 = value.model_dir) != null ? ref6 : null;
          adapterPath = (ref7 = value.adapter_path) != null ? ref7 : null;
          resumeAdapterFile = (ref8 = value.resume_adapter_file) != null ? ref8 : null;
          trainingDir = (ref9 = value.training_dir) != null ? ref9 : null;
          stdoutText = (ref10 = value.stdout_text) != null ? ref10 : null;
          trainRowsCount = (ref11 = value.train_rows_count) != null ? ref11 : null;
          validRowsCount = (ref12 = value.valid_rows_count) != null ? ref12 : null;
          testRowsCount = (ref13 = value.test_rows_count) != null ? ref13 : null;
          checkpointPath = (ref14 = value.checkpoint_path) != null ? ref14 : null;
          db.exec('BEGIN');
          try {
            db.prepare(`INSERT INTO lora_training_runs (
  run_id, started_at, finished_at, status, model_dir, adapter_path,
  resume_adapter_file, training_dir, stdout_text, train_rows_count,
  valid_rows_count, test_rows_count, checkpoint_path
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(run_id) DO UPDATE SET
  started_at = excluded.started_at,
  finished_at = excluded.finished_at,
  status = excluded.status,
  model_dir = excluded.model_dir,
  adapter_path = excluded.adapter_path,
  resume_adapter_file = excluded.resume_adapter_file,
  training_dir = excluded.training_dir,
  stdout_text = excluded.stdout_text,
  train_rows_count = excluded.train_rows_count,
  valid_rows_count = excluded.valid_rows_count,
  test_rows_count = excluded.test_rows_count,
  checkpoint_path = excluded.checkpoint_path`).run(writeRunID,
      startedAt,
      finishedAt,
      status,
      modelDir,
      adapterPath,
      resumeAdapterFile,
      trainingDir,
      stdoutText,
      trainRowsCount,
      validRowsCount,
      testRowsCount,
      checkpointPath);
            db.prepare(`DELETE FROM lora_training_run_stories
WHERE run_id = ?`).run(writeRunID);
            insertStory = db.prepare(`INSERT INTO lora_training_run_stories (run_id, story_id)
VALUES (?, ?)`);
            ref15 = value.story_ids;
            for (i = 0, len = ref15.length; i < len; i++) {
              storyID = ref15[i];
              if (storyID == null) {
                throw new Error("sqlite meta loraTrainingRun story_ids contain empty value");
              }
              insertStory.run(writeRunID,
      storyID);
              db.prepare(`INSERT INTO lora_story_usage (story_id, use_count, last_trained_at, last_run_id)
VALUES (?, 1, ?, ?)
ON CONFLICT(story_id) DO UPDATE SET
  use_count = lora_story_usage.use_count + 1,
  last_trained_at = excluded.last_trained_at,
  last_run_id = excluded.last_run_id`).run(storyID,
      finishedAt != null ? finishedAt : startedAt,
      writeRunID);
            }
            db.exec('COMMIT');
          } catch (error) {
            err = error;
            try {
              db.exec('ROLLBACK');
            } catch (error) {
              null;
            }
            throw err;
          }
          return {
            run_id: writeRunID,
            started_at: startedAt,
            finished_at: finishedAt,
            status: status,
            model_dir: modelDir,
            adapter_path: adapterPath,
            resume_adapter_file: resumeAdapterFile,
            training_dir: trainingDir,
            stdout_text: stdoutText,
            train_rows_count: trainRowsCount,
            valid_rows_count: validRowsCount,
            test_rows_count: testRowsCount,
            checkpoint_path: checkpointPath,
            story_ids: value.story_ids
          };
        }
      },
      {
        name: 'loraTrainingRuns',
        regex: /^loraTrainingRuns$/,
        allowedSuffixes: ['jsonl',
      'txt',
      'csv'],
        read: function(db) {
          return db.prepare(`SELECT
  run_id,
  started_at,
  finished_at,
  status,
  model_dir,
  adapter_path,
  training_dir,
  train_rows_count,
  valid_rows_count,
  test_rows_count,
  checkpoint_path
FROM lora_training_runs
ORDER BY started_at DESC, run_id DESC`).all();
        },
        write: null
      }
    ];
    return M.addMetaRule("sqlite", /^(?:storyByID\{[^}]+\}|partsFor\{[^}]+\}|kagFor\{[^}]+\}|expandedPartsFor\{[^}]+\}|storiesWithKag\{[^}]+\}|storiesMissingKag|allStories|trainedStories|loraStoryUsage|loraTrainingRun\{[^}]+\}|loraTrainingRuns)\.(json|jsonl|txt|csv)$/i, function(key, value) {
      var decoded, formatter, i, len, match, matchedArgs, matchedRequest, request, requestKey, result, suffix, suffixMatch;
      debugLog("meta key", key, "write?", value !== void 0);
      suffixMatch = key.match(/\.([A-Za-z0-9]+)$/);
      if (suffixMatch == null) {
        return void 0;
      }
      suffix = suffixMatch[1].toLowerCase();
      formatter = FORMATTERS[suffix];
      if (formatter == null) {
        return void 0;
      }
      requestKey = key.replace(/\.[A-Za-z0-9]+$/, '');
      debugLog("parsed", `requestKey=${requestKey}`, `suffix=${suffix}`);
      matchedRequest = null;
      matchedArgs = null;
      for (i = 0, len = REQUESTS.length; i < len; i++) {
        request = REQUESTS[i];
        match = requestKey.match(request.regex);
        debugLog("regex check", request.name, String(request.regex), `matched=${!!match}`);
        if (match == null) {
          continue;
        }
        matchedRequest = request;
        matchedArgs = match.slice(1);
        break;
      }
      if (matchedRequest == null) {
        debugLog("no sqlite request match", requestKey);
        return void 0;
      }
      if (!matchedRequest.allowedSuffixes.includes(suffix)) {
        throw new Error(`sqlite meta request ${matchedRequest.name} does not allow .${suffix}`);
      }
      debugLog("matched request", matchedRequest.name, `args=${JSON.stringify(matchedArgs)}`);
      if (value === void 0) {
        debugLog("read start", matchedRequest.name, `args=${JSON.stringify(matchedArgs)}`);
        result = matchedRequest.read(db, ...matchedArgs);
        if (Array.isArray(result)) {
          debugLog("read result", matchedRequest.name, `rows=${result.length}`);
        } else {
          debugLog("read result", matchedRequest.name, `type=${typeof result}`);
        }
        return formatter.read(result);
      }
      if (typeof matchedRequest.write !== 'function') {
        throw new Error(`sqlite meta request ${matchedRequest.name} is read-only`);
      }
      decoded = formatter.write(value);
      if (Array.isArray(decoded)) {
        debugLog("write start", matchedRequest.name, `args=${JSON.stringify(matchedArgs)}`, `rows=${decoded.length}`);
      } else {
        debugLog("write start", matchedRequest.name, `args=${JSON.stringify(matchedArgs)}`, `type=${typeof decoded}`);
      }
      matchedRequest.write(db, decoded, ...matchedArgs);
      return debugLog("write done", matchedRequest.name, `args=${JSON.stringify(matchedArgs)}`);
    });
  };

}).call(this);
