// Generated by CoffeeScript 2.7.0
(function() {
  var joinParagraphs;

  joinParagraphs = function(items) {
    var i, item, len, parts, text;
    parts = [];
    for (i = 0, len = items.length; i < len; i++) {
      item = items[i];
      if (item == null) {
        continue;
      }
      text = `${item}`.trim();
      if (!(text.length > 0)) {
        continue;
      }
      parts.push(text);
    }
    return parts.join("\n");
  };

  this.step = {
    desc: "Assemble sqlite-backed expanded parts into story scaffold",
    action: async function(S) {
      var expanded, expandedParts, ref, ref1, ref10, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, storyID, text;
      storyID = (await S.need('selected_story_id'));
      if (typeof storyID !== 'string') {
        throw new Error(`[${S.stepName}] selected_story_id must be a string`);
      }
      expanded = (ref = S.theLowdown(`expandedPartsFor{${storyID}}.json`)) != null ? ref.value : void 0;
      if ((expanded != null ? expanded.expanded_parts : void 0) == null) {
        throw new Error(`[${S.stepName}] Missing sqlite expanded parts ${storyID}`);
      }
      expandedParts = expanded.expanded_parts;
      text = joinParagraphs(["scene - " + ((ref1 = (ref2 = expandedParts.scene) != null ? ref2.text : void 0) != null ? ref1 : ''), "arrival -  " + ((ref3 = (ref4 = expandedParts.arrival) != null ? ref4.text : void 0) != null ? ref3 : ''), "disturbance - " + ((ref5 = (ref6 = expandedParts.disturbance) != null ? ref6.text : void 0) != null ? ref5 : ''), "reflection - " + ((ref7 = (ref8 = expandedParts.reflection) != null ? ref8.text : void 0) != null ? ref7 : ''), "realization - " + ((ref9 = (ref10 = expandedParts.realization) != null ? ref10.text : void 0) != null ? ref9 : '')]);
      S.make('story', {
        story_id: storyID,
        text: text,
        parts: expanded
      });
      S.done();
    }
  };

}).call(this);
