// Generated by CoffeeScript 2.7.0
(function() {
  var renderKagEntry;

  renderKagEntry = function(entry) {
    var headline, keyword, ref, ref1;
    keyword = String((ref = entry != null ? entry.keyword : void 0) != null ? ref : '').trim();
    headline = String((ref1 = entry != null ? entry.headline : void 0) != null ? ref1 : '').trim();
    if (!(keyword.length || headline.length)) {
      return null;
    }
    if (keyword.length && headline.length) {
      return `- ${keyword}: ${headline}`;
    }
    if (keyword.length) {
      return `- ${keyword}`;
    }
    return `- ${headline}`;
  };

  this.step = {
    desc: "Build a KAG-augmented prompt for final story generation",
    action: async function(S) {
      var entry, i, kag, kagLines, len, prompt, ref, ref1, ref2, ref3, rendered, story, storyID, storyRecord;
      storyID = (await S.need('selected_story_id'));
      story = (await S.need('story'));
      if (typeof storyID !== 'string') {
        throw new Error(`[${S.stepName}] selected_story_id must be a string`);
      }
      if ((story != null ? story.text : void 0) == null) {
        throw new Error(`[${S.stepName}] story must be an object`);
      }
      storyRecord = (ref = S.theLowdown(`storyByID{${storyID}}.json`)) != null ? ref.value : void 0;
      kag = (ref1 = S.theLowdown(`kagFor{${storyID}}.json`)) != null ? ref1.value : void 0;
      if ((storyRecord != null ? storyRecord.text : void 0) == null) {
        throw new Error(`[${S.stepName}] Missing sqlite story ${storyID}`);
      }
      if (!Array.isArray(kag != null ? kag.entries : void 0)) {
        throw new Error(`[${S.stepName}] Missing sqlite KAG ${storyID}`);
      }
      kagLines = [];
      ref2 = kag.entries;
      for (i = 0, len = ref2.length; i < len; i++) {
        entry = ref2[i];
        rendered = renderKagEntry(entry);
        if (rendered != null) {
          kagLines.push(rendered);
        }
      }
      prompt = ["You are writing in the narrative voice of Jim from St. John's.", "", "Use the following KAG emotional/event cues to guide the story.", "Keep the story grounded in the source material and preserve the event order already present in the scaffold.", "", "KAG cues:", kagLines.length ? kagLines.join("\n") : "- none", "", "Rules:", "- Speak in the first person as Jim", "- Keep the same order of events", "- Do not introduce new plot elements that contradict the scaffold", "- Add natural narration and sensory detail", "- Keep the tone observational, slightly humorous, and reflective", "- Return only the finished story", "", "Source title:", `${(ref3 = storyRecord.title) != null ? ref3 : storyID}`, "", "Story scaffold:", "", `${story.text}`].join("\n");
      S.make('kag_prompt_text', prompt);
      S.done();
    }
  };

}).call(this);
