// Generated by CoffeeScript 2.7.0
(function() {
  var headlineAt, keywordAt;

  headlineAt = function(entries, idx, fallback) {
    var entry, headline, ref;
    entry = entries[idx];
    if (entry == null) {
      return fallback;
    }
    headline = String((ref = entry.headline) != null ? ref : '').trim();
    if (!headline.length) {
      return fallback;
    }
    return headline;
  };

  keywordAt = function(entries, idx, fallback) {
    var entry, keyword, ref;
    entry = entries[idx];
    if (entry == null) {
      return fallback;
    }
    keyword = String((ref = entry.keyword) != null ? ref : '').trim();
    if (!keyword.length) {
      return fallback;
    }
    return keyword;
  };

  this.step = {
    desc: "Create five canonical story events from sqlite KAG entries",
    action: async function(S) {
      var entries, kag, parts, ref, ref1, ref2, story, storyID, title;
      storyID = (await S.need('selected_story_id'));
      if (typeof storyID !== 'string') {
        throw new Error(`[${S.stepName}] selected_story_id must be a string`);
      }
      story = (ref = S.theLowdown(`storyByID{${storyID}}.json`)) != null ? ref.value : void 0;
      kag = (ref1 = S.theLowdown(`kagFor{${storyID}}.json`)) != null ? ref1.value : void 0;
      if ((story != null ? story.text : void 0) == null) {
        throw new Error(`[${S.stepName}] Missing sqlite story ${storyID}`);
      }
      if (!(Array.isArray(kag != null ? kag.entries : void 0) && kag.entries.length > 0)) {
        throw new Error(`[${S.stepName}] Missing sqlite KAG ${storyID}`);
      }
      entries = kag.entries;
      title = String((ref2 = story.title) != null ? ref2 : storyID).trim();
      parts = {
        scene: {
          text: `daylight around ${title} felt touched by ${headlineAt(entries, 0, 'a quiet but unusual mood')}`,
          location: title
        },
        arrival: {
          text: `the feeling of ${keywordAt(entries, 1, keywordAt(entries, 0, 'change'))} arrived with ${headlineAt(entries, 1, 'a person who brought new energy')}`,
          character: keywordAt(entries, 1, 'visitor')
        },
        disturbance: {
          text: headlineAt(entries, 2, headlineAt(entries, 0, 'the calm gave way to a disturbance worth noticing')),
          theme: keywordAt(entries, 2, keywordAt(entries, 0, 'tension'))
        },
        reflection: {
          text: `I kept turning over ${headlineAt(entries, 3, headlineAt(entries, 1, 'what the moment might mean'))}`
        },
        realization: {
          text: headlineAt(entries, 4, headlineAt(entries, 2, 'something finally became clear to me'))
        }
      };
      S.saveThis(`partsFor{${storyID}}.json`, {
        story_id: storyID,
        parts: parts
      });
      S.done();
    }
  };

}).call(this);
