// Generated by CoffeeScript 2.7.0
(function() {
  var capitalizeFirst, ensureSentence, expandArrival, expandDisturbance, expandRealization, expandReflection, expandScene, lowerFirst;

  ensureSentence = function(s) {
    var last, text;
    if (s == null) {
      return '';
    }
    text = `${s}`.trim();
    if (!(text.length > 0)) {
      return '';
    }
    last = text.charAt(text.length - 1);
    if (last !== '.' && last !== '!' && last !== '?') {
      text = text + '.';
    }
    return text;
  };

  capitalizeFirst = function(s) {
    var text;
    if (s == null) {
      return '';
    }
    text = `${s}`.trim();
    if (!(text.length > 0)) {
      return '';
    }
    return text.charAt(0).toUpperCase() + text.slice(1);
  };

  lowerFirst = function(s) {
    var text;
    if (s == null) {
      return '';
    }
    text = `${s}`.trim();
    if (!(text.length > 0)) {
      return '';
    }
    return text.charAt(0).toLowerCase() + text.slice(1);
  };

  expandScene = function(part) {
    var raw, ref, ref1, ref2, text;
    raw = lowerFirst((ref = part != null ? part.text : void 0) != null ? ref : '');
    text = ensureSentence(`The ${raw}`);
    return {
      text: text,
      source_text: (ref1 = part != null ? part.text : void 0) != null ? ref1 : '',
      location: (ref2 = part != null ? part.location : void 0) != null ? ref2 : null,
      expansion_mode: 'scene_narration'
    };
  };

  expandArrival = function(part) {
    var ref, ref1, ref2, text;
    text = ensureSentence(capitalizeFirst((ref = part != null ? part.text : void 0) != null ? ref : ''));
    return {
      text: text,
      source_text: (ref1 = part != null ? part.text : void 0) != null ? ref1 : '',
      character: (ref2 = part != null ? part.character : void 0) != null ? ref2 : null,
      expansion_mode: 'arrival_narration'
    };
  };

  expandDisturbance = function(part) {
    var raw, ref, ref1, ref2, text;
    raw = lowerFirst((ref = part != null ? part.text : void 0) != null ? ref : '');
    text = ensureSentence(`On the radio, ${raw}`);
    return {
      text: text,
      source_text: (ref1 = part != null ? part.text : void 0) != null ? ref1 : '',
      theme: (ref2 = part != null ? part.theme : void 0) != null ? ref2 : null,
      expansion_mode: 'disturbance_narration'
    };
  };

  expandReflection = function(part) {
    var ref, ref1, text;
    text = ensureSentence(capitalizeFirst((ref = part != null ? part.text : void 0) != null ? ref : ''));
    return {
      text: text,
      source_text: (ref1 = part != null ? part.text : void 0) != null ? ref1 : '',
      expansion_mode: 'reflection_narration'
    };
  };

  expandRealization = function(part) {
    var raw, ref, ref1, text;
    raw = lowerFirst((ref = part != null ? part.text : void 0) != null ? ref : '');
    text = ensureSentence(`That was when I realized ${raw}`);
    return {
      text: text,
      source_text: (ref1 = part != null ? part.text : void 0) != null ? ref1 : '',
      expansion_mode: 'realization_narration'
    };
  };

  this.step = {
    desc: "Expand sqlite-backed story events into fuller prose parts",
    action: async function(S) {
      var expandedParts, ref, storyID, storyParts;
      storyID = (await S.need('selected_story_id'));
      if (typeof storyID !== 'string') {
        throw new Error(`[${S.stepName}] selected_story_id must be a string`);
      }
      storyParts = (ref = S.theLowdown(`partsFor{${storyID}}.json`)) != null ? ref.value : void 0;
      if ((storyParts != null ? storyParts.parts : void 0) == null) {
        throw new Error(`[${S.stepName}] Missing sqlite story parts ${storyID}`);
      }
      expandedParts = {
        scene: expandScene(storyParts.parts.scene),
        arrival: expandArrival(storyParts.parts.arrival),
        disturbance: expandDisturbance(storyParts.parts.disturbance),
        reflection: expandReflection(storyParts.parts.reflection),
        realization: expandRealization(storyParts.parts.realization)
      };
      S.saveThis(`expandedPartsFor{${storyID}}.json`, {
        story_id: storyID,
        expanded_parts: expandedParts
      });
      S.done();
    }
  };

}).call(this);
