// Generated by CoffeeScript 2.7.0
(function() {
  this.step = {
    desc: "Select a SQLite-backed story for KAG-assisted generation",
    action: function(S) {
      var kag, ref, ref1, story, storyID;
      storyID = S.param('story_id');
      if (storyID == null) {
        throw new Error(`[${S.stepName}] Missing story_id param`);
      }
      story = (ref = S.theLowdown(`storyByID{${storyID}}.json`)) != null ? ref.value : void 0;
      if ((story != null ? story.story_id : void 0) !== storyID) {
        throw new Error(`[${S.stepName}] Missing sqlite story ${storyID}`);
      }
      kag = (ref1 = S.theLowdown(`kagFor{${storyID}}.json`)) != null ? ref1.value : void 0;
      if (!(Array.isArray(kag != null ? kag.entries : void 0) && kag.entries.length > 0)) {
        throw new Error(`[${S.stepName}] Missing sqlite KAG ${storyID}`);
      }
      S.make('selected_story_id', storyID);
      S.done();
    }
  };

}).call(this);
