#pragma once

extern "C" {
const char* rusty_mlx_shim_version();
int rusty_mlx_shim_probe();
int rusty_mlx_link_probe();
unsigned long long rusty_mlx_create_test_array();
double rusty_mlx_test_array_sum(unsigned long long handle);
int rusty_mlx_free_test_array(unsigned long long handle);
const char* rusty_mlx_runtime_diagnose_json();
unsigned long long rusty_mlx_create_token_array(const unsigned long long* tokens, unsigned long long length);
const char* rusty_mlx_token_array_info_json(unsigned long long handle);
int rusty_mlx_free_token_array(unsigned long long handle);
unsigned long long rusty_mlx_mock_forward(unsigned long long session_handle, unsigned long long token_array_handle);
unsigned long long rusty_mlx_mock_sample(unsigned long long logits_handle);
const char* rusty_mlx_array_info_json(unsigned long long handle);
int rusty_mlx_free_array(unsigned long long handle);
const char* rusty_mlx_handle_counts_json();
int rusty_mlx_load_tensor_group(const char* handle, const char* model_dir, const char* group);
const char* rusty_mlx_tensor_group_info_json(const char* handle);
const char* rusty_mlx_quantization_layout_probe_json(const char* handle);
int rusty_mlx_free_tensor_group(const char* handle);
int rusty_mlx_load_embedding_group(const char* handle, const char* model_dir);
const char* rusty_mlx_embedding_group_info_json(const char* handle);
int rusty_mlx_free_embedding_group(const char* handle);
const char* rusty_mlx_compare_dequant_slice_json(const char* handle, unsigned long long row, unsigned long long cols);
const char* rusty_mlx_quantized_linear_slice_probe_json(const char* handle, const double* input, unsigned long long input_length, unsigned long long row, unsigned long long cols);
const char* rusty_mlx_quantized_linear_rows_probe_json(const char* handle, const double* input, unsigned long long input_length, unsigned long long rows, unsigned long long cols);
const char* rusty_mlx_quantized_linear_fullrow_probe_json(const char* handle, const double* input, unsigned long long input_length, unsigned long long rows);
const char* rusty_mlx_quantized_linear_vector_probe_json(const char* handle, const double* input, unsigned long long input_length);
const char* rusty_mlx_rmsnorm_probe_json(const char* handle, const double* input, unsigned long long input_length);
const char* rusty_mlx_layer0_single_token_probe_json(const char* model_dir, unsigned long long token_id);
const char* rusty_mlx_layer0_mlp_probe_json(const char* model_dir, unsigned long long token_id);
const char* rusty_mlx_layer0_block_probe_json(const char* model_dir, unsigned long long token_id);
const char* rusty_mlx_layer_stack_probe_json(const char* model_dir, unsigned long long token_id, unsigned long long layers);
const char* rusty_mlx_full_stack_single_token_probe_json(const char* model_dir, unsigned long long token_id);
const char* rusty_mlx_kv_cache_storage_probe_json();
const char* rusty_mlx_incremental_attention_probe_json(const char* model_dir, unsigned long long prompt_token_id, unsigned long long decode_token_id);
const char* rusty_mlx_session_layer_residency_probe_json(const char* model_dir, unsigned long long prompt_token_id, unsigned long long decode_token_id);
const char* rusty_mlx_fastsmoke_generation_probe_json(const char* model_dir, unsigned long long prompt_token_id, const char* prompt_token_ids_csv, unsigned long long first_decode_token_id, unsigned long long generated_tokens);
const char* rusty_mlx_resident_incremental_timing_breakdown_probe_json(const char* model_dir, unsigned long long decode_token_id);
const char* rusty_mlx_quantized_linear_kernel_probe_json(const char* model_dir);
const char* rusty_mlx_quantized_linear_mlx_probe_json(const char* model_dir);
const char* rusty_mlx_metal_first_resident_decode_probe_json(const char* model_dir, unsigned long long prompt_token_id, unsigned long long decode_token_id);
const char* rusty_mlx_resident_incremental_optimized_compare_probe_json(const char* model_dir, unsigned long long decode_token_id);
const char* rusty_mlx_resident_incremental_layout_cached_compare_probe_json(const char* model_dir, unsigned long long decode_token_id);
const char* rusty_mlx_resident_incremental_mlp_optimized_compare_probe_json(const char* model_dir, unsigned long long decode_token_id);
const char* rusty_mlx_resident_incremental_logits_optimized_compare_probe_json(const char* model_dir, unsigned long long decode_token_id);
const char* rusty_mlx_resident_incremental_down_full_block_compare_probe_json(const char* model_dir, unsigned long long decode_token_id);
const char* rusty_mlx_resident_incremental_gate_up_full_block_compare_probe_json(const char* model_dir, unsigned long long decode_token_id);
const char* rusty_mlx_greedy_next_token_probe_json(const char* model_dir, unsigned long long token_id);
const char* rusty_mlx_greedy_two_token_probe_json(const char* model_dir, unsigned long long token_id);
unsigned long long rusty_mlx_dequantize_group_slice(const char* handle, unsigned long long rows, unsigned long long cols);
int rusty_mlx_load_layer_groups(const char* handle, const char* model_dir, int layer);
const char* rusty_mlx_layer_groups_info_json(const char* handle);
int rusty_mlx_free_layer_groups(const char* handle);
}
