// Generated by CoffeeScript 2.7.0
(function() {
  this.step = {
    desc: "Persist LoRA training usage and run metadata through SQLite meta keys",
    action: async function(M, stepName) {
      var experiment, i, len, payload, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, row, runEntry, runRecord, runRecordTarget, selectedEntry, selectedStoryIDs, storyID, targetEntry, targetValue, trainedStoryIDs, usageEntry, usageRows, useCount;
      selectedEntry = M.theLowdown('selected_story_ids');
      selectedStoryIDs = selectedEntry != null ? selectedEntry.value : void 0;
      if (selectedStoryIDs === void 0) {
        if (typeof (selectedEntry != null ? selectedEntry.waitFor : void 0) === 'function') {
          selectedStoryIDs = (await selectedEntry.waitFor());
        } else if ((selectedEntry != null ? selectedEntry.notifier : void 0) != null) {
          selectedStoryIDs = (await selectedEntry.notifier);
        }
      }
      runEntry = M.theLowdown('lora_run_record');
      runRecord = runEntry != null ? runEntry.value : void 0;
      if (runRecord === void 0) {
        if (typeof (runEntry != null ? runEntry.waitFor : void 0) === 'function') {
          runRecord = (await runEntry.waitFor());
        } else if ((runEntry != null ? runEntry.notifier : void 0) != null) {
          runRecord = (await runEntry.notifier);
        }
      }
      if (!((runRecord != null) && typeof runRecord === 'object' && !Array.isArray(runRecord))) {
        experiment = (ref = (ref1 = M.theLowdown('experiment.yaml')) != null ? ref1.value : void 0) != null ? ref : {};
        runRecordTarget = experiment != null ? (ref2 = experiment.artifacts) != null ? (ref3 = ref2.lora_run_record) != null ? ref3.target : void 0 : void 0 : void 0;
        if (typeof runRecordTarget === 'string') {
          targetEntry = M.theLowdown(runRecordTarget);
          targetValue = targetEntry != null ? targetEntry.value : void 0;
          if (targetValue === void 0) {
            if (typeof (targetEntry != null ? targetEntry.waitFor : void 0) === 'function') {
              targetValue = (await targetEntry.waitFor());
            } else if ((targetEntry != null ? targetEntry.notifier : void 0) != null) {
              targetValue = (await targetEntry.notifier);
            }
          }
          if ((targetValue != null) && typeof targetValue === 'object' && !Array.isArray(targetValue)) {
            runRecord = targetValue;
          }
        }
      }
      if (!Array.isArray(selectedStoryIDs)) {
        throw new Error(`[${stepName}] selected_story_ids must be an array`);
      }
      if (!((runRecord != null) && typeof runRecord === 'object' && !Array.isArray(runRecord))) {
        throw new Error(`[${stepName}] lora_run_record must be an object`);
      }
      if (runRecord.run_id == null) {
        throw new Error(`[${stepName}] lora_run_record missing run_id`);
      }
      payload = {
        run_id: runRecord.run_id,
        started_at: (ref4 = runRecord.started_at) != null ? ref4 : null,
        finished_at: (ref5 = runRecord.finished_at) != null ? ref5 : null,
        status: (ref6 = runRecord.status) != null ? ref6 : 'done',
        model_dir: (ref7 = runRecord.model_dir) != null ? ref7 : null,
        adapter_path: (ref8 = runRecord.adapter_path) != null ? ref8 : null,
        resume_adapter_file: (ref9 = runRecord.resume_adapter_file) != null ? ref9 : null,
        training_dir: (ref10 = runRecord.training_dir) != null ? ref10 : null,
        stdout_text: (ref11 = runRecord.stdout_text) != null ? ref11 : null,
        train_rows_count: (ref12 = runRecord.train_rows_count) != null ? ref12 : null,
        valid_rows_count: (ref13 = runRecord.valid_rows_count) != null ? ref13 : null,
        test_rows_count: (ref14 = runRecord.test_rows_count) != null ? ref14 : null,
        checkpoint_path: (ref15 = runRecord.checkpoint_path) != null ? ref15 : null,
        story_ids: selectedStoryIDs
      };
      M.saveThis(`loraTrainingRun{${payload.run_id}}.json`, payload);
      usageEntry = M.theLowdown('loraStoryUsage.jsonl');
      usageRows = usageEntry != null ? usageEntry.value : void 0;
      if (usageRows === void 0) {
        if (typeof (usageEntry != null ? usageEntry.waitFor : void 0) === 'function') {
          usageRows = (await usageEntry.waitFor());
        } else if ((usageEntry != null ? usageEntry.notifier : void 0) != null) {
          usageRows = (await usageEntry.notifier);
        }
      }
      if (!Array.isArray(usageRows)) {
        throw new Error(`[${stepName}] loraStoryUsage.jsonl must be an array`);
      }
      trainedStoryIDs = [];
      for (i = 0, len = usageRows.length; i < len; i++) {
        row = usageRows[i];
        storyID = row != null ? row.story_id : void 0;
        useCount = (ref16 = row != null ? row.use_count : void 0) != null ? ref16 : 0;
        if (storyID == null) {
          continue;
        }
        if (!(useCount > 0)) {
          continue;
        }
        trainedStoryIDs.push(storyID);
      }
      console.log("[record_lora_training_ite] run id:", payload.run_id);
      console.log("[record_lora_training_ite] recorded stories:", selectedStoryIDs.length);
      console.log("[record_lora_training_ite] total stories with LoRA usage:", trainedStoryIDs.length);
      M.saveThis('trained_story_ids', trainedStoryIDs);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
