// Generated by CoffeeScript 2.7.0
(function() {
  this.step = {
    desc: "Persist LoRA training usage and run metadata through SQLite meta keys",
    action: async function(M, stepName) {
      var i, len, payload, ref, ref1, ref10, ref11, ref12, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, row, runEntry, runRecord, selectedEntry, selectedStoryIDs, storyID, trainedStoryIDs, usageEntry, usageRows, useCount;
      selectedEntry = M.theLowdown('selected_story_ids');
      selectedStoryIDs = selectedEntry != null ? selectedEntry.value : void 0;
      if (selectedStoryIDs === void 0) {
        if (typeof (selectedEntry != null ? selectedEntry.waitFor : void 0) === 'function') {
          selectedStoryIDs = (await selectedEntry.waitFor());
        } else if ((selectedEntry != null ? selectedEntry.notifier : void 0) != null) {
          selectedStoryIDs = (await selectedEntry.notifier);
        }
      }
      runEntry = M.theLowdown('lora_run_record');
      runRecord = runEntry != null ? runEntry.value : void 0;
      if (runRecord === void 0) {
        if (typeof (runEntry != null ? runEntry.waitFor : void 0) === 'function') {
          runRecord = (await runEntry.waitFor());
        } else if ((runEntry != null ? runEntry.notifier : void 0) != null) {
          runRecord = (await runEntry.notifier);
        }
      }
      if (!Array.isArray(selectedStoryIDs)) {
        throw new Error(`[${stepName}] selected_story_ids must be an array`);
      }
      if (!((runRecord != null) && typeof runRecord === 'object' && !Array.isArray(runRecord))) {
        throw new Error(`[${stepName}] lora_run_record must be an object`);
      }
      if (runRecord.run_id == null) {
        throw new Error(`[${stepName}] lora_run_record missing run_id`);
      }
      payload = {
        run_id: runRecord.run_id,
        started_at: (ref = runRecord.started_at) != null ? ref : null,
        finished_at: (ref1 = runRecord.finished_at) != null ? ref1 : null,
        status: (ref2 = runRecord.status) != null ? ref2 : 'done',
        model_dir: (ref3 = runRecord.model_dir) != null ? ref3 : null,
        adapter_path: (ref4 = runRecord.adapter_path) != null ? ref4 : null,
        resume_adapter_file: (ref5 = runRecord.resume_adapter_file) != null ? ref5 : null,
        training_dir: (ref6 = runRecord.training_dir) != null ? ref6 : null,
        stdout_text: (ref7 = runRecord.stdout_text) != null ? ref7 : null,
        train_rows_count: (ref8 = runRecord.train_rows_count) != null ? ref8 : null,
        valid_rows_count: (ref9 = runRecord.valid_rows_count) != null ? ref9 : null,
        test_rows_count: (ref10 = runRecord.test_rows_count) != null ? ref10 : null,
        checkpoint_path: (ref11 = runRecord.checkpoint_path) != null ? ref11 : null,
        story_ids: selectedStoryIDs
      };
      M.saveThis(`loraTrainingRun{${payload.run_id}}.json`, payload);
      usageEntry = M.theLowdown('loraStoryUsage.jsonl');
      usageRows = usageEntry != null ? usageEntry.value : void 0;
      if (usageRows === void 0) {
        if (typeof (usageEntry != null ? usageEntry.waitFor : void 0) === 'function') {
          usageRows = (await usageEntry.waitFor());
        } else if ((usageEntry != null ? usageEntry.notifier : void 0) != null) {
          usageRows = (await usageEntry.notifier);
        }
      }
      if (!Array.isArray(usageRows)) {
        throw new Error(`[${stepName}] loraStoryUsage.jsonl must be an array`);
      }
      trainedStoryIDs = [];
      for (i = 0, len = usageRows.length; i < len; i++) {
        row = usageRows[i];
        storyID = row != null ? row.story_id : void 0;
        useCount = (ref12 = row != null ? row.use_count : void 0) != null ? ref12 : 0;
        if (storyID == null) {
          continue;
        }
        if (!(useCount > 0)) {
          continue;
        }
        trainedStoryIDs.push(storyID);
      }
      console.log("[record_lora_training_ite] run id:", payload.run_id);
      console.log("[record_lora_training_ite] recorded stories:", selectedStoryIDs.length);
      console.log("[record_lora_training_ite] total stories with LoRA usage:", trainedStoryIDs.length);
      M.saveThis('trained_story_ids', trainedStoryIDs);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
