// Generated by CoffeeScript 2.7.0
(function() {
  var detectCheckpointPath, fs, hasAdapterConfig, path, resolveResumeFile;

  fs = require('fs');

  path = require('path');

  resolveResumeFile = function(adapterPath, configuredResumeFile) {
    var checkpoints, finalAdapter;
    if ((configuredResumeFile != null) && fs.existsSync(configuredResumeFile)) {
      return configuredResumeFile;
    }
    if (!((adapterPath != null) && fs.existsSync(adapterPath))) {
      return null;
    }
    finalAdapter = path.join(adapterPath, 'adapters.safetensors');
    if (fs.existsSync(finalAdapter)) {
      return finalAdapter;
    }
    checkpoints = fs.readdirSync(adapterPath).filter(function(name) {
      return /^\d+_adapters\.safetensors$/.test(name);
    }).sort();
    if (!checkpoints.length) {
      return null;
    }
    return path.join(adapterPath, checkpoints[checkpoints.length - 1]);
  };

  detectCheckpointPath = function(adapterPath) {
    var checkpoints, finalAdapter;
    if (!((adapterPath != null) && fs.existsSync(adapterPath))) {
      return null;
    }
    finalAdapter = path.join(adapterPath, 'adapters.safetensors');
    if (fs.existsSync(finalAdapter)) {
      return finalAdapter;
    }
    checkpoints = fs.readdirSync(adapterPath).filter(function(name) {
      return /^\d+_adapters\.safetensors$/.test(name);
    }).sort();
    if (!checkpoints.length) {
      return null;
    }
    return path.join(adapterPath, checkpoints[checkpoints.length - 1]);
  };

  hasAdapterConfig = function(adapterPath) {
    if (adapterPath == null) {
      return false;
    }
    return fs.existsSync(path.join(adapterPath, 'adapter_config.json'));
  };

  this.step = {
    desc: "Run MLX LoRA training using direct Memo access",
    action: async function(M, stepName) {
      var actualResumeFile, adapterConfigExists, adapterPath, args, checkpointPath, explicitModelDir, finishedAt, mlxDebug, modelDir, modelMemoKey, ref, ref1, ref2, resumeFile, runID, runRecord, startedAt, stdoutText, testEntry, testOnly, testRows, trainEntry, trainRows, trainingDir, validEntry, validRows;
      trainEntry = M.theLowdown('train_rows');
      trainRows = trainEntry != null ? trainEntry.value : void 0;
      if (trainRows === void 0) {
        if (typeof (trainEntry != null ? trainEntry.waitFor : void 0) === 'function') {
          trainRows = (await trainEntry.waitFor());
        } else if ((trainEntry != null ? trainEntry.notifier : void 0) != null) {
          trainRows = (await trainEntry.notifier);
        }
      }
      validEntry = M.theLowdown('valid_rows');
      validRows = validEntry != null ? validEntry.value : void 0;
      if (validRows === void 0) {
        if (typeof (validEntry != null ? validEntry.waitFor : void 0) === 'function') {
          validRows = (await validEntry.waitFor());
        } else if ((validEntry != null ? validEntry.notifier : void 0) != null) {
          validRows = (await validEntry.notifier);
        }
      }
      testEntry = M.theLowdown('test_rows');
      testRows = testEntry != null ? testEntry.value : void 0;
      if (testRows === void 0) {
        if (typeof (testEntry != null ? testEntry.waitFor : void 0) === 'function') {
          testRows = (await testEntry.waitFor());
        } else if ((testEntry != null ? testEntry.notifier : void 0) != null) {
          testRows = (await testEntry.notifier);
        }
      }
      if (!Array.isArray(trainRows)) {
        throw new Error(`[${stepName}] train_rows must be an array`);
      }
      if (!Array.isArray(validRows)) {
        throw new Error(`[${stepName}] valid_rows must be an array`);
      }
      if (!Array.isArray(testRows)) {
        throw new Error(`[${stepName}] test_rows must be an array`);
      }
      testOnly = M.getStepParam(stepName, 'test_only');
      if (testOnly === void 0) {
        testOnly = false;
      }
      adapterPath = M.getStepParam(stepName, 'adapter_path');
      resumeFile = M.getStepParam(stepName, 'resume_adapter_file');
      modelMemoKey = M.getStepParam(stepName, 'model_memo_key');
      if (modelMemoKey === void 0) {
        modelMemoKey = 'modelDir';
      }
      explicitModelDir = M.getStepParam(stepName, 'model_dir');
      trainingDir = M.getStepParam(stepName, 'training_dir');
      modelDir = (ref = explicitModelDir != null ? explicitModelDir : (ref1 = M.theLowdown(modelMemoKey)) != null ? ref1.value : void 0) != null ? ref : (ref2 = M.theLowdown('modelDir')) != null ? ref2.value : void 0;
      if (modelDir == null) {
        throw new Error(`[${stepName}] Missing model directory`);
      }
      if (trainingDir == null) {
        throw new Error(`[${stepName}] Missing training_dir`);
      }
      actualResumeFile = resolveResumeFile(adapterPath, resumeFile);
      adapterConfigExists = hasAdapterConfig(adapterPath);
      args = {
        model: modelDir,
        data: trainingDir
      };
      if (testOnly) {
        args.test = null;
        console.log("[run_lora_train_ite] mode: test");
      } else {
        args.train = null;
        console.log("[run_lora_train_ite] mode: train");
      }
      if (testOnly) {
        if (adapterConfigExists) {
          args["adapter-path"] = adapterPath;
        } else {
          console.log("[run_lora_train_ite] no adapter_config.json at:", adapterPath);
        }
      } else {
        args["adapter-path"] = adapterPath;
      }
      if ((actualResumeFile != null) && !testOnly) {
        args["resume-adapter-file"] = actualResumeFile;
      }
      startedAt = new Date().toISOString();
      runID = `lora-${startedAt.replace(/[:.]/g, '-')}`;
      mlxDebug = M.getStepParam(stepName, 'debug_mlx');
      if (mlxDebug === void 0) {
        mlxDebug = false;
      }
      stdoutText = M.callMLX('lora', args, mlxDebug);
      finishedAt = new Date().toISOString();
      checkpointPath = detectCheckpointPath(adapterPath);
      runRecord = {
        run_id: runID,
        started_at: startedAt,
        finished_at: finishedAt,
        status: 'done',
        model_dir: modelDir,
        adapter_path: adapterPath,
        resume_adapter_file: actualResumeFile,
        training_dir: trainingDir,
        stdout_text: stdoutText,
        train_rows_count: trainRows.length,
        valid_rows_count: validRows.length,
        test_rows_count: testRows.length,
        checkpoint_path: checkpointPath
      };
      console.log("[run_lora_train_ite] train rows:", trainRows.length);
      console.log("[run_lora_train_ite] valid rows:", validRows.length);
      console.log("[run_lora_train_ite] test rows:", testRows.length);
      console.log("[run_lora_train_ite] run id:", runID);
      M.saveThis('lora_stdout', stdoutText);
      M.saveThis('lora_run_record', runRecord);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
