// Generated by CoffeeScript 2.7.0
(function() {
  this.step = {
    desc: "Select a small SQLite-backed story batch for LoRA training",
    action: async function(M, stepName) {
      var batchSize, i, idx, j, len, len1, row, selectedStoryIDs, storyID, usageEntry, usageRows;
      batchSize = M.getStepParam(stepName, 'batch_size');
      usageEntry = M.theLowdown('loraStoryUsage.jsonl');
      usageRows = usageEntry != null ? usageEntry.value : void 0;
      if (usageRows === void 0) {
        if (typeof (usageEntry != null ? usageEntry.waitFor : void 0) === 'function') {
          usageRows = (await usageEntry.waitFor());
        } else if ((usageEntry != null ? usageEntry.notifier : void 0) != null) {
          usageRows = (await usageEntry.notifier);
        }
      }
      if (!Array.isArray(usageRows)) {
        throw new Error(`[${stepName}] loraStoryUsage.jsonl must be an array`);
      }
      selectedStoryIDs = [];
      for (i = 0, len = usageRows.length; i < len; i++) {
        row = usageRows[i];
        storyID = row != null ? row.story_id : void 0;
        if (storyID == null) {
          continue;
        }
        selectedStoryIDs.push(storyID);
        if (selectedStoryIDs.length >= batchSize) {
          break;
        }
      }
      console.log("[select_lora_stories_ite] usage rows:", usageRows.length);
      console.log("[select_lora_stories_ite] selected batch size:", selectedStoryIDs.length);
      for (idx = j = 0, len1 = selectedStoryIDs.length; j < len1; idx = ++j) {
        storyID = selectedStoryIDs[idx];
        console.log(`[select_lora_stories_ite] batch[${idx}] ${storyID}`);
      }
      M.saveThis('selected_story_ids', selectedStoryIDs);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
