// Generated by CoffeeScript 2.7.0
(function() {
  var buildFragmentParagraphs, estimateTokens, pre_prompt, sanitizeStop;

  pre_prompt = `You are writing in the narrative voice of Jim from St. John's.

Expand the following story fragment into a complete reflective narrative.

Maintain the same events and ideas, but improve flow, imagery, and voice.

Rules:
- Speak in the first person as Jim
- Keep the same order of events
- Do not introduce new plot elements
- Add natural narration and sensory detail
- The tone should be observational, slightly humorous, and reflective
- Return only the finished story

Story fragment:`;

  estimateTokens = function(text) {
    var cleaned;
    if (text == null) {
      return 0;
    }
    cleaned = String(text).trim();
    if (!(cleaned.length > 0)) {
      return 0;
    }
    return Math.ceil(cleaned.length / 4);
  };

  buildFragmentParagraphs = function(paragraphs) {
    var currentLen, currentText, firstPara, ref, ref1, rval, secondPara;
    rval = [];
    if (!Array.isArray(paragraphs)) {
      return rval;
    }
    if (paragraphs.length === 0) {
      return rval;
    }
    firstPara = (ref = paragraphs[0]) != null ? ref : '';
    if (firstPara.trim().length > 0) {
      rval.push(firstPara.trim());
    }
    currentText = rval.join("\n\n");
    currentLen = currentText.length;
    if (currentLen < 300 && paragraphs.length > 1) {
      secondPara = (ref1 = paragraphs[1]) != null ? ref1 : '';
      if (secondPara.trim().length > 0) {
        rval.push(secondPara.trim());
      }
    }
    return rval;
  };

  sanitizeStop = function(text) {
    var rval;
    rval = String(text != null ? text : '');
    rval = rval.replace(/(?:\s*<stop>\s*)+$/g, '');
    return rval.trim();
  };

  this.step = {
    desc: "Build MLX training rows from SQLite-backed full stories",
    action: async function(S) {
      var MAX_TOTAL_TOKENS, SAFETY_TOKENS, STOP_TEXT, STOP_TOKENS, chunkParagraphs, chunkTokens, cleanPara, cleanSentence, completionParagraphs, completionStartIndex, completionText, flushChunk, fragmentParagraphs, fragmentText, fullStoryText, i, idx, isLastSentenceChunk, j, k, l, len, len1, len2, len3, maxCompletionTokens, newStoryIds, para, paraTokens, paragraphs, prompt, promptTokens, proposedSentenceTokens, proposedTokens, rawParagraphs, ref, ref1, rows, rowsWritten, sentTokens, sentence, sentenceChunk, sentenceTokens, sentences, storiesProcessed, story, storyID, textOut;
      newStoryIds = (await S.need('new_story_ids'));
      if (!Array.isArray(newStoryIds)) {
        throw new Error(`[${S.stepName}] new_story_ids must be an array`);
      }
      if (newStoryIds.length === 0) {
        console.log("[prepare_training_data_sqlite] stories processed: 0");
        console.log("[prepare_training_data_sqlite] rows written: 0");
        S.make('train_rows', []);
        S.make('valid_rows', []);
        S.make('test_rows', []);
        S.done();
        return;
      }
      rows = [];
      rowsWritten = 0;
      storiesProcessed = 0;
      MAX_TOTAL_TOKENS = 1024;
      SAFETY_TOKENS = 64;
      STOP_TEXT = "\n\n<stop>";
      STOP_TOKENS = estimateTokens(STOP_TEXT);
      for (i = 0, len = newStoryIds.length; i < len; i++) {
        storyID = newStoryIds[i];
        if (storyID == null) {
          continue;
        }
        story = (ref = S.theLowdown(`storyByID{${storyID}}.json`)) != null ? ref.value : void 0;
        if (story == null) {
          throw new Error(`[${S.stepName}] missing storyByID for ${storyID}`);
        }
        fullStoryText = String((ref1 = story.text) != null ? ref1 : '').trim();
        if (!(fullStoryText.length > 0)) {
          continue;
        }
        rawParagraphs = fullStoryText.split(/\n\s*\n/);
        paragraphs = [];
        for (j = 0, len1 = rawParagraphs.length; j < len1; j++) {
          para = rawParagraphs[j];
          cleanPara = String(para != null ? para : '').trim();
          if (!(cleanPara.length > 0)) {
            continue;
          }
          paragraphs.push(cleanPara);
        }
        if (!(paragraphs.length > 0)) {
          continue;
        }
        fragmentParagraphs = buildFragmentParagraphs(paragraphs);
        if (!(fragmentParagraphs.length > 0)) {
          continue;
        }
        fragmentText = fragmentParagraphs.join("\n\n");
        prompt = pre_prompt + fragmentText + "\n\nBegin:\n\n";
        promptTokens = estimateTokens(prompt);
        completionStartIndex = fragmentParagraphs.length;
        completionParagraphs = paragraphs.slice(completionStartIndex);
        if (completionParagraphs.length === 0) {
          textOut = prompt.trim() + STOP_TEXT;
          rows.push({
            text: textOut
          });
          rowsWritten += 1;
          storiesProcessed += 1;
          continue;
        }
        maxCompletionTokens = MAX_TOTAL_TOKENS - promptTokens - SAFETY_TOKENS - STOP_TOKENS;
        if (maxCompletionTokens < 80) {
          throw new Error(`[${S.stepName}] prompt too large for token budget on story ${storyID}`);
        }
        chunkParagraphs = [];
        chunkTokens = 0;
        flushChunk = function(isLastChunk) {
          var completionText;
          if (!(chunkParagraphs.length > 0)) {
            return;
          }
          completionText = chunkParagraphs.join("\n\n");
          completionText = sanitizeStop(completionText);
          textOut = prompt + completionText;
          if (isLastChunk) {
            textOut = sanitizeStop(textOut) + STOP_TEXT;
          }
          rows.push({
            text: textOut
          });
          rowsWritten += 1;
          chunkParagraphs = [];
          chunkTokens = 0;
        };
        for (idx = k = 0, len2 = completionParagraphs.length; k < len2; idx = ++k) {
          para = completionParagraphs[idx];
          paraTokens = estimateTokens(para);
          proposedTokens = chunkTokens + paraTokens;
          if (chunkParagraphs.length > 0 && proposedTokens > maxCompletionTokens) {
            flushChunk(false);
          }
          if (paraTokens > maxCompletionTokens) {
            sentences = para.split(/(?<=[.!?])\s+/);
            sentenceChunk = [];
            sentenceTokens = 0;
            for (l = 0, len3 = sentences.length; l < len3; l++) {
              sentence = sentences[l];
              cleanSentence = String(sentence != null ? sentence : '').trim();
              if (!(cleanSentence.length > 0)) {
                continue;
              }
              sentTokens = estimateTokens(cleanSentence);
              proposedSentenceTokens = sentenceTokens + sentTokens;
              if (sentenceChunk.length > 0 && proposedSentenceTokens > maxCompletionTokens) {
                completionText = sentenceChunk.join(" ");
                textOut = prompt + completionText;
                rows.push({
                  text: textOut
                });
                rowsWritten += 1;
                sentenceChunk = [];
                sentenceTokens = 0;
              }
              sentenceChunk.push(cleanSentence);
              sentenceTokens += sentTokens;
            }
            if (sentenceChunk.length > 0) {
              isLastSentenceChunk = idx === completionParagraphs.length - 1;
              completionText = sentenceChunk.join(" ");
              completionText = sanitizeStop(completionText);
              textOut = prompt + completionText;
              if (isLastSentenceChunk) {
                textOut = sanitizeStop(textOut) + STOP_TEXT;
              }
              rows.push({
                text: textOut
              });
              rowsWritten += 1;
            }
            continue;
          }
          chunkParagraphs.push(para);
          chunkTokens += paraTokens;
        }
        if (chunkParagraphs.length > 0) {
          flushChunk(true);
        }
        storiesProcessed += 1;
      }
      console.log("[prepare_training_data_sqlite] stories processed:", storiesProcessed);
      console.log("[prepare_training_data_sqlite] rows written:", rowsWritten);
      S.make('train_rows', rows);
      S.make('valid_rows', rows);
      S.make('test_rows', rows);
      S.done();
    }
  };

}).call(this);
