// Generated by CoffeeScript 2.7.0
(function() {
  this.step = {
    desc: "Record the completed SQLite-backed LoRA training batch",
    action: async function(S) {
      var i, idx, j, k, len, len1, len2, mergedRows, newStoryIds, ref, ref1, row, seen, stamp, storyID, trainedAt, trainedRows;
      newStoryIds = (await S.need('new_story_ids'));
      trainedRows = (ref = S.theLowdown('trainedStories.jsonl')) != null ? ref.value : void 0;
      if (trainedRows === void 0) {
        trainedRows = [];
      }
      if (!Array.isArray(newStoryIds)) {
        throw new Error(`[${S.stepName}] new_story_ids must be an array`);
      }
      if (!Array.isArray(trainedRows)) {
        throw new Error(`[${S.stepName}] trainedStories.jsonl must be an array`);
      }
      mergedRows = [];
      seen = new Set();
      for (i = 0, len = trainedRows.length; i < len; i++) {
        row = trainedRows[i];
        if (typeof row === 'string') {
          storyID = row;
          trainedAt = null;
        } else {
          storyID = row != null ? row.story_id : void 0;
          trainedAt = (ref1 = row != null ? row.trained_at : void 0) != null ? ref1 : null;
        }
        if (storyID == null) {
          continue;
        }
        if (seen.has(storyID)) {
          continue;
        }
        seen.add(storyID);
        mergedRows.push({
          story_id: storyID,
          trained_at: trainedAt
        });
      }
      stamp = new Date().toISOString();
      for (j = 0, len1 = newStoryIds.length; j < len1; j++) {
        storyID = newStoryIds[j];
        if (storyID == null) {
          continue;
        }
        if (seen.has(storyID)) {
          continue;
        }
        seen.add(storyID);
        mergedRows.push({
          story_id: storyID,
          trained_at: stamp
        });
      }
      console.log("[record_trained_batch_sqlite] previous trained stories:", trainedRows.length);
      console.log("[record_trained_batch_sqlite] current batch stories:", newStoryIds.length);
      console.log("[record_trained_batch_sqlite] total trained stories:", mergedRows.length);
      for (idx = k = 0, len2 = newStoryIds.length; k < len2; idx = ++k) {
        storyID = newStoryIds[idx];
        if (storyID != null) {
          console.log(`[record_trained_batch_sqlite] trained[${idx}] ${storyID}`);
        }
      }
      S.saveThis('trainedStories.jsonl', mergedRows);
      S.make('trained_story_ids', (function() {
        var l, len3, results;
        results = [];
        for (l = 0, len3 = mergedRows.length; l < len3; l++) {
          row = mergedRows[l];
          results.push(row.story_id);
        }
        return results;
      })());
      S.done();
    }
  };

}).call(this);
