// Generated by CoffeeScript 2.7.0
(function() {
  this.step = {
    desc: "Select the next batch of SQLite-backed stories for LoRA training",
    action: function(S) {
      var batchIDs, batchSize, i, idx, j, k, len, len1, len2, ref, ref1, row, stories, storiesLeft, story, storyID, trainedRows, trainedSet, unseenCount;
      batchSize = S.param('batch_size');
      stories = (ref = S.theLowdown('allStories.jsonl')) != null ? ref.value : void 0;
      trainedRows = (ref1 = S.theLowdown('trainedStories.jsonl')) != null ? ref1.value : void 0;
      if (!Array.isArray(stories)) {
        throw new Error(`[${S.stepName}] allStories.jsonl must be an array`);
      }
      if (trainedRows === void 0) {
        trainedRows = [];
      }
      if (!Array.isArray(trainedRows)) {
        throw new Error(`[${S.stepName}] trainedStories.jsonl must be an array`);
      }
      trainedSet = new Set();
      for (i = 0, len = trainedRows.length; i < len; i++) {
        row = trainedRows[i];
        if (typeof row === 'string') {
          trainedSet.add(row);
        } else {
          storyID = row != null ? row.story_id : void 0;
          if (storyID != null) {
            trainedSet.add(storyID);
          }
        }
      }
      batchIDs = [];
      unseenCount = 0;
      for (j = 0, len1 = stories.length; j < len1; j++) {
        story = stories[j];
        storyID = story != null ? story.story_id : void 0;
        if (storyID == null) {
          continue;
        }
        if (!trainedSet.has(storyID)) {
          unseenCount += 1;
          if (batchIDs.length < batchSize) {
            batchIDs.push(storyID);
          }
        }
      }
      storiesLeft = Math.max(unseenCount - batchIDs.length, 0);
      console.log("[select_training_batch_sqlite] total unseen stories:", unseenCount);
      console.log("[select_training_batch_sqlite] already trained stories:", trainedSet.size);
      console.log("[select_training_batch_sqlite] selected batch size:", batchIDs.length);
      console.log("[select_training_batch_sqlite] stories left after this batch:", storiesLeft);
      for (idx = k = 0, len2 = batchIDs.length; k < len2; idx = ++k) {
        storyID = batchIDs[idx];
        console.log(`[select_training_batch_sqlite] batch[${idx}] ${storyID}`);
      }
      S.make('new_story_ids', batchIDs);
      S.done();
    }
  };

}).call(this);
