run:
  model: Qwen/Qwen3-4B-Instruct-2507
  output_dir: out
  data_dir: data
  training_dir: build/train
  loraLand: build/model
  debug_s: false
  debug_mlx: false
  debug_sql: false

artifacts: {}

download_model:
  run: story/hf_download.coffee
  depends_on: []
  needs: []
  makes: []
  loraLand: build/model

quantize_model:
  run: kag_oracle/quantize_model.coffee
  depends_on: [download_model]
  needs: []
  makes: []
  source_model_dir: build/model
  quantized_model_dir: build/model4
  quantized_model_memo_key: quantizedModelDir
  mlx:
    q: null
    q-bits: 4
