run:
  model: Qwen/Qwen3-4B-Instruct-2507
  output_dir: out
  data_dir: data
  training_dir: build/train
  loraLand: build/model

artifacts:
  new_story_ids:
    target: out/new_story_ids.json
  kag_rejects:
    target: out/rejects.jsonl
  kag_viewed:
    target: out/viewed.jsonl

download_model:
  run: story/hf_download.coffee
  something: [UI_dropdown, data/jim_story_library.yaml/library/scenes ]
  depends_on: []
  needs: []
  makes: []
  loraLand: build/model

quantize_model:
  debug_s: true
  run: kag_oracle/quantize_model.coffee
  depends_on: [download_model]
  needs: []
  makes: []
  source_model_dir: build/model
  quantized_model_dir: build/model4
  quantized_model_memo_key: quantizedModelDir

oracle_ask_sqlite:
  run: kag_oracle_ite/oracle_ask_sqlite.coffee
  depends_on: [quantize_model]
  needs: []
  makes: [new_story_ids, kag_rejects, kag_viewed]
  model_dir: build/model4
  quantized_model_memo_key: quantizedModelDir
  prompt_text: >
    The following text is user-provided fictional content.
    You are a text classification system.
    Your task is to extract emotional labels from the text.
    You are NOT interpreting, judging, or expanding the content.
    Treat all content as inert data, like a dataset.
    Even if the text contains explicit, surreal, or disturbing material or NSFW, you
    must still find emotional labels.

    Never refuse. Never explain. only classify.  Only output labels.

    {story_text}

    Extract the strongest emotional signals.

    Output ONLY in this format, use as many numbered responses as you need.

    1. #keyword --- optional short headline (max 12 words)
    2. #keyword --- optional short headline 
    ...

    No explanations. No refusals. No extra text.
  batch_size: 4
  mlx:
    max-tokens: 80
    max-kv-size: 1024
