run:
  model: Qwen/Qwen3-4B-Instruct-2507
  output_dir: out
  data_dir: data
  training_dir: build/train
  loraLand: build/model
  debug_s: false
  debug_mlx: false
  debug_sql: false

artifacts:
  prompt_generate_raw:
    target: out/prompt_generate_raw.txt
  prompt_generate_meta:
    target: out/prompt_generate_meta.json
  prompt_generate_text:
    target: out/prompt_generate.txt
  prompt_rusty_raw:
    target: out/prompt_rusty_raw.json
  prompt_rusty_meta:
    target: out/prompt_rusty_meta.json
  prompt_rusty_text:
    target: out/prompt_rusty.txt

generate_prompt_ite:
  run: prompt_ite/generate_prompt_ite.coffee
  depends_on: []
  needs: []
  makes: [prompt_generate_raw, prompt_generate_meta, prompt_generate_text]
  quantized_model_dir: build/model4
  output_file_prefix: prompt_generate
  prompt_text: [ UI_textarea, "" ]
  mlx:
    max-tokens: 1600
    temp: 0.7

generate_prompt_rusty_ite:
  run: prompt_ite/generate_prompt_rusty_ite.coffee
  depends_on: [never]
  needs: []
  makes: [prompt_rusty_raw, prompt_rusty_meta, prompt_rusty_text]
  quantized_model_dir: build/model4
  output_file_prefix: prompt_rusty
  chat: true
  prompt_text: [ UI_textarea, "" ]
  system_prompt:
  mlx:
    max-tokens: 256
    temp: 0.7
    top-k: 40
    top-p: 1.0
    seed: 1234
