// Generated by CoffeeScript 2.7.0
(function() {
  this.step = {
    desc: "Extract structured KAG fields for prompt caching",
    action: async function(M, stepName) {
      var out, ref, ref1, ref2, ref3, ref4, ref5, row, sampleIndex, sourceEntry, sourceKey, sourceRows;
      sourceKey = M.getStepParam(stepName, 'kag_source_key');
      sampleIndex = M.getStepParam(stepName, 'sample_index');
      sampleIndex = parseInt(sampleIndex, 10);
      if (Number.isNaN(sampleIndex)) {
        sampleIndex = 0;
      }
      sourceEntry = M.theLowdown(sourceKey);
      sourceRows = sourceEntry != null ? sourceEntry.value : void 0;
      if (sourceRows === void 0) {
        sourceRows = (await sourceEntry.notifier);
      }
      if (sourceRows === void 0) {
        throw new Error(`[${stepName}] Missing input key '${sourceKey}'`);
      }
      if (!Array.isArray(sourceRows)) {
        throw new Error(`[${stepName}] ${sourceKey} must be an array`);
      }
      if (!(sourceRows.length > 0)) {
        throw new Error(`[${stepName}] ${sourceKey} is empty`);
      }
      row = sourceRows[sampleIndex];
      if (row == null) {
        throw new Error(`[${stepName}] sample_index ${sampleIndex} is out of range`);
      }
      out = {
        story_id: (ref = row != null ? (ref1 = row.meta) != null ? ref1.doc_id : void 0 : void 0) != null ? ref : null,
        source_index: sampleIndex,
        source_meta: (ref2 = row != null ? row.meta : void 0) != null ? ref2 : {},
        fields: {
          source_prompt: (ref3 = (ref4 = row != null ? row.prompt : void 0) != null ? ref4 : row != null ? row.text : void 0) != null ? ref3 : null,
          emotions: (ref5 = row != null ? row.emotions : void 0) != null ? ref5 : {}
        }
      };
      M.saveThis("kag_record", out);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
