// Generated by CoffeeScript 2.7.0
(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  this.step = {
    desc: "Build paragraph-level KAG input records from segments and emotion tags",
    action: async function(M, stepName) {
      var docId, emotionRows, emotions, emotionsEntry, emotionsKey, i, j, len, len1, lookup, matched, outputPath, paragraphIndex, ref, ref1, ref2, ref3, ref4, row, rowsWritten, segment, stories, storiesEntry, storiesKey, text, title;
      storiesKey = M.getStepParam(stepName, 'marshalled_stories');
      emotionsKey = M.getStepParam(stepName, 'kag_emotions');
      outputPath = M.getStepParam(stepName, 'kag_segments');
      storiesEntry = M.theLowdown(storiesKey);
      stories = storiesEntry != null ? storiesEntry.value : void 0;
      if (stories === void 0) {
        stories = (await storiesEntry.notifier);
      }
      emotionsEntry = M.theLowdown(emotionsKey);
      emotionRows = emotionsEntry != null ? emotionsEntry.value : void 0;
      if (emotionRows === void 0) {
        emotionRows = (await emotionsEntry.notifier);
      }
      if (!Array.isArray(stories)) {
        throw new Error(`[${stepName}] ${storiesKey} must be an array`);
      }
      if (!Array.isArray(emotionRows)) {
        throw new Error(`[${stepName}] ${emotionsKey} must be an array`);
      }
      lookup = Object.create(null);
      for (i = 0, len = emotionRows.length; i < len; i++) {
        row = emotionRows[i];
        docId = row != null ? (ref = row.meta) != null ? ref.doc_id : void 0 : void 0;
        paragraphIndex = row != null ? (ref1 = row.meta) != null ? ref1.paragraph_index : void 0 : void 0;
        emotions = row != null ? row.emotions : void 0;
        if (docId == null) {
          continue;
        }
        if (paragraphIndex == null) {
          continue;
        }
        if (emotions == null) {
          continue;
        }
        lookup[`${docId}|${paragraphIndex}`] = emotions;
      }
      fs.mkdirSync(path.dirname(outputPath), {
        recursive: true
      });
      fs.writeFileSync(outputPath, '', 'utf8');
      matched = 0;
      rowsWritten = 0;
      for (j = 0, len1 = stories.length; j < len1; j++) {
        segment = stories[j];
        docId = segment != null ? (ref2 = segment.meta) != null ? ref2.doc_id : void 0 : void 0;
        paragraphIndex = segment != null ? (ref3 = segment.meta) != null ? ref3.paragraph_index : void 0 : void 0;
        title = segment != null ? (ref4 = segment.meta) != null ? ref4.title : void 0 : void 0;
        text = segment != null ? segment.text : void 0;
        if (docId == null) {
          continue;
        }
        if (paragraphIndex == null) {
          continue;
        }
        if (title == null) {
          continue;
        }
        if (text == null) {
          continue;
        }
        emotions = lookup[`${docId}|${paragraphIndex}`];
        if (emotions == null) {
          continue;
        }
        matched += 1;
        row = {
          meta: {
            doc_id: docId,
            paragraph_index: paragraphIndex,
            title: title
          },
          text: text,
          emotions: emotions
        };
        fs.appendFileSync(outputPath, JSON.stringify(row) + "\n", 'utf8');
        rowsWritten += 1;
      }
      console.log("[prepare_kag_segments] segments matched:", matched);
      console.log("[prepare_kag_segments] rows written:", rowsWritten);
      M.saveThis(`done:${stepName}`, true);
    }
  };

}).call(this);
